### ISSUE TITLE
Clarity on shortcut for moving files in normal mode

### ISSUE THREAD

**Issue by benfrain** [nvim-telescope/telescope-file-browser.nvim#10]
### Description

Could you clarify what `--/m` means in terms of the default shortcut needed to move a file(s) in normal mode?

In the readme/docs, each action has a `<C-*>` mapping for normal mode, apart from move. 

### Neovim version

```markdown
NVIM v0.6.0-dev+2040-g8cbe100fc
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.6.1

### Steps to reproduce

select some files
navigate to target folder
try and use the default shortcut to move

### Expected behavior

A `<C-M>` shortcut or similar

### Actual behavior

Typing `--` just enters that string into the text input box.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Terminal emulators cannot distinguish between `<C-m>` and `<CR>`; therefore, there is no analog for moving a file with `ctrl` prefix from insert mode as of now and you can only move multi-selected files to the target directory from within normal mode.

**Comment by benfrain** [comment]
Hmm. I suppose I would expect it to have something mapped. Even if users may want to change it. I’m going to trial <C-S> for ‘Shift’ or <C-V> for ‘moVe’. Will see how it sticks and what it conflicts with! 👍
Thanks for the clarity.

**Comment by fdschmidt93** [comment]
> Hmm. I suppose I would expect it to have something mapped. 

I understand. It's also not that well know as to why `<C-m>` cannot be mapped (e.g. it came up a couple of times already in telescope-core as well).

I'll do my best to invest a bit more significant time again into the release prior to deprecating the file browser upstream. Then, I'll carefully revisit the defaults mappings once more.

Unfortunately, I'm quite preoccupied at the moment for more serious work.
