### ISSUE TITLE
A shortcut to open buffer as split

### ISSUE THREAD

**Issue by ForteDexe** [nvim-telescope/telescope-file-browser.nvim#101]
**Is your feature request related to a problem? Please describe.**
It is an inconvenience that opens the file as a new tab, then splits it.

**Describe the solution you'd like**
A shortcut.

**Describe alternatives you've considered**
I think it can write in function, but I am new to Lua, definitely cost a lot of time to figure out. You can write an example code and put it in a doc, so a newbie can follow it.

**Comment by fdschmidt93** [comment]
> It is an inconvenience that opens the file as a new tab, then splits it.

I don't follow what that means since I don't think aligns with `(n)vim` terminology.

> A shortcut to open buffer as split

https://github.com/nvim-telescope/telescope.nvim#default-mappings

In any case, it's all there. Any telescope picker inherits mappings from the global configuration.

**Comment by ForteDexe** [comment]
Oops my bad, thank you @fdschmidt93.
