### ISSUE TITLE
Picker option path = "%:p:h" wont work

### ISSUE THREAD

**Issue by zer09** [nvim-telescope/telescope-file-browser.nvim#106]
### Description

I have this telescope config
```lua
telescope.setup({
	defaults = {
		prompt_prefix = "❯ ",
		selection_caret = "❯ ",
		file_ignore_patterns = { "node_modules/.*", "%.env" },
		mappings = {
			i = {
				["<esc>"] = actions.close,
				["<C-u>"] = false,
			},
		},
	},
	pickers = {
		file_browser = {
			path = "%:p:h",
		},
	},
	extensions = {},
})
```

While the file_browser path value is "%:p:h" it will still open the browser from the root directory

### Neovim version

```markdown
NVIM v0.7.0-dev+1132-g15004473b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

5.16.7-1-MANJARO

### Steps to reproduce

1. Setting the picker file_browser path option to "%:p:h"
2. calling `:Telescope file_browser` without any argument
3. It open the file browser to the root directory

### Expected behavior

It should open the file browser on the current buffer file location

### Actual behavior

It open the file browser to the root directory

### Minimal config

```Lua
local helper = require("helper")
local map = helper.map
local telescope = require("telescope")
local actions = require("telescope.actions")

map("n", "<Leader>ff", ":Telescope fd<CR>")
map("n", "<Leader>fb", ":Telescope file_browser<CR>")
map("n", "<Leader>bb", ":Telescope buffers<CR>")
map("n", "<Leader>fg", ":Telescope live_grep<CR>")
map("n", "<Leader>fh", ":Telescope help_tags<CR>")
map("n", "<Leader>fm", ":Telescope keymaps<CR>")

telescope.setup({
	defaults = {
		prompt_prefix = "❯ ",
		selection_caret = "❯ ",
		file_ignore_patterns = { "node_modules/.*", "%.env" },
		mappings = {
			i = {
				["<esc>"] = actions.close,
				["<C-u>"] = false,
			},
		},
	},
	pickers = {
		file_browser = {
			path = "%:p:h",
		},
	},
	extensions = {},
})

telescope.load_extension("fzf")
telescope.load_extension("file_browser")
```

**Comment by jamestrew** [comment]
Put the `path` setting under the `extensions.file_browser` like so:
```lua
telescope.setup({
	defaults = {
		prompt_prefix = "❯ ",
		selection_caret = "❯ ",
		file_ignore_patterns = { "node_modules/.*", "%.env" },
		mappings = {
			i = {
				["<esc>"] = actions.close,
				["<C-u>"] = false,
			},
		},
	},
	extensions = {,
            file_browser = {
              path = "%:p:h",
            },
          }
}

```

**Comment by zer09** [comment]
@jamestrew Thanks you so much it works

I think I just miss look the readme.

> If you want to open the file_browser from within the folder of your current buffer, you should pass path = "%:p:h" to the opts table of the **_picker_** (Vimscript: :Telescope file_browser path=%:p:h) or to the extension setup configuration. Strings passed to path or cwd are expanded automatically.

I thought it should be put on picker
