### ISSUE TITLE
Custom 'move' keybind overrides '<cr>'

### ISSUE THREAD

**Issue by barrett-ruth** [nvim-telescope/telescope-file-browser.nvim#110]
### Description

I don't like the default alt bindings (by the way, why do these exist? no other plugin I know of uses alt/meta instead of control, including telescope itself) so I wanted to remap them to control in insert mode.

Everything works but 'fb_actions.move' in insert mode, which nullifies the use of enter to open files

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Operating system and version

arch

### Steps to reproduce

1. nvim -nu minimal.lua
2. ':Telescope file_browser'
3. Press enter on a file in insert mode
4. Witness pain

### Expected behavior

Pressing enter in insert mode opens the file/goes into the directory

### Actual behavior

Nothing!

Note that enter in NORMAL mode behaves properly.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup {
        {
            'wbthomason/packer.nvim',
            {
                'nvim-telescope/telescope.nvim',
                requires = {
                    'nvim-lua/plenary.nvim',
                    'nvim-telescope/telescope-file-browser.nvim',
                },
            },
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        },
    }
end
_G.load_config = function()
    require('telescope').setup {
        extensions = {
            file_browser = {
                mappings = {
                    i = {
                        ['<c-m>'] = require('telescope').extensions.file_browser.actions.move,
                    },
                },
            },
        },
    }
    require('telescope').load_extension 'file_browser'
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
    print 'Installing Telescope and dependencies.'
    vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
`<C-m>` is equivalent to `<CR>` or the enter key in linux terminals so binding it to actions like that won't result in the behavior you except.

As for the rest of the default bindings, we went through a couple iterations, getting feedback and landed on what we have currently. Trying to get the right mix of not utterly overwritting the default mappings of the basic telescope as well as accommodating common bindings used for other file managers/explorers such as `nvim-tree.lua`. We simply have too many relevant actions to bind with just `ctrl` for insert mode as you've demonstrated for yourself.

**Comment by barrett-ruth** [comment]
I should've known. I tested out Control-V Control-M but not Control-V Enter to see what it would send. 
Thanks, I'll just set it up to another binding that works.
