### ISSUE TITLE
Tab completion support

### ISSUE THREAD

**Issue by srid** [nvim-telescope/telescope-file-browser.nvim#127]
**Is your feature request related to a problem? Please describe.**
When I hit `c`, it prompts me for filename, but I can't use TAB completion to complete sub directories before entering the filename. Instead when I press TAB I see `^I` injected:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3998/165306200-8d0c2bc3-1e0c-4b21-8d2c-922f497acdfc.png">

**Describe the solution you'd like**
Pressing TAB should complete the subdirectories or files in that path.

**Describe alternatives you've considered**
Manually type in the sub path name.

**Comment by fdschmidt93** [comment]
I'm currently working in #118 on reusing the telescope prompt for the file input with something like this

https://user-images.githubusercontent.com/39233597/165178718-c1bde432-5c3a-43bc-9837-72142a2b0530.mp4

(it's already revised a bit and works better now)

which will enable you to complete file paths within the currently opened directory by means of telescope selection.

That said, file/folder creation of `telescope-file-browser` is primarily intended to be performed within the currently opened folder of the `file_browser`. Of course, generating a file in other folders is possibly, but that would make completion a bit more tricky.

I'll see what I can do, but that might have to wait until a later iteration (as I'm working on the stuff in the video as means to leverage `telescope` for `vim.ui.input`).

**Comment by fdschmidt93** [comment]
Apologies, I was overthinking this a bit in my efforts to leverage telescope prompt for `vim.ui.input` :) With `dressing.nvim` and the default implementation tab completion now should work nicely. Let me know in case there's any issues.
