### ISSUE TITLE
File browser specific file_ignore patterns

### ISSUE THREAD

**Issue by sebffischer** [nvim-telescope/telescope-file-browser.nvim#14]
It would be great if the file_browser had the option "file_ignore_pattern" that overwrites the default file_ignore pattern. 
In my special case there is a `NAMESPACE` file that I don't want to live-grep over but which I would like to see in the file-browser. 
Maybe this is a more general feature request and not only related to the file-browser, if so please redirect this issue.

**Comment by fdschmidt93** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/6b1579741a0e8f1e0e63d0c6c364b968c157338e/lua/telescope/pickers.lua#L99

Does it work if you just set an empty table for `file_ignore_patterns` (`get_default` here is essentially `vim.F.if_nil`). Then, it should work if you just set `file_ignore_patterns` to an empty table in the config as in the README, I think.

**Comment by sebffischer** [comment]
Thank you for your quick answer, it was just my lacking lua and neovim skills ...

**Comment by sebffischer** [comment]
But for a beginner like me it is not really obvious from the docs

**Comment by fdschmidt93** [comment]
Absolutely no worries, this comes up from time to time. And probably only from time to time, because most people just don't set that parameter :)
