### ISSUE TITLE
Directories name don't show up

### ISSUE THREAD

**Issue by c3n21** [nvim-telescope/telescope-file-browser.nvim#145]
### Description

Hello!

I just switched to this file browser but I'm having this issue with directories name not showing up.

I've already tried using older NeoVim versions

### Neovim version

```markdown
NVIM v0.8.0-dev+334-ge9803e1de
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux

### Steps to reproduce

Run `Telescope file_browser`

### Expected behavior

It should show directory names like in the screenshots of the repo

### Actual behavior

![image](https://user-images.githubusercontent.com/37077738/170956839-f49ce84c-f04a-4346-9f31-fda5783a93ae.png)

As you can see directory names don't show up

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Huh, thanks for reporting. My very first hunch is that something about `fd` changed? That would be odd though, but I only noticed it myself too now.

For instance, forcing `telescope-file-browser` to use `plenary.scandir` via `:Telescope file_browser grouped=true` shows the directory names.

Looking into this right away!

**Comment by fdschmidt93** [comment]
I would have to check what exactly has caused this, but I've pushed a fix now via https://github.com/nvim-telescope/telescope-file-browser.nvim/commit/e84b24030c567e48acfe8a00aedee66f793c3f56

which fixes the problem for me for both `plenary` and `fd` file_browser finders. Please let me know whether the issue is resolved for you as well!

**Comment by c3n21** [comment]
Wow that was fast!

Now it works like a charm, thanks a lot
