### ISSUE TITLE
SVG files show mangled names 

### ISSUE THREAD

**Issue by benfrain** [nvim-telescope/telescope-file-browser.nvim#157]
### Description

Think file browser is choking on the SVG files, and mangling the names (although Preview shows the file content correctly).

Files named like this:

'bb-ball.svg' in macOS finder

Are being displayed like:

's.nocIepacsdnaL9*' in Telescope File Browser. The same file names appear correct in 'normal' Telescope.

I still see the issue if I set `preview = false` in the Telescope config. Mention this as it initially seemed like https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/133

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
```

### Operating system and version

macOS 12.4

### Steps to reproduce

1. Use macOS (don't have anything with another OS)
2. open File Browser and look for SVG files in a folder
3. Observe names are mangled

### Expected behavior

Names in File Browser appear the same as in the standard Telescope

### Actual behavior

SVG file names appear mangled

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
I'm afraid I cannot reproduce with both `plenary` and `fd` finder on my and minimal init lua.

![image](https://user-images.githubusercontent.com/39233597/177518267-7c91baa1-1949-4b20-8856-98b0bc6db60b.png)

SVG is from [wikipedia](https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg).
