### ISSUE TITLE
default <c-t> binding conflicts with telescope's function to open in new tab

### ISSUE THREAD

**Issue by MetriC-DT** [nvim-telescope/telescope-file-browser.nvim#164]
`<c-t>` keybind should not override the telescope keybind to open in new tab.

**Comment by fdschmidt93** [comment]
3rd issue on this topic. The plugin has lots of default mappings for discoverability. Naturally, some will conflict. See link on how to restore original mapping

https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/102#issuecomment-1047753097

I'll eventually revisit default mappings again, but this topic consumes a lot of time with the least clear marginal gain, as everyone has individual preferences.

Please consider searching through issues next time beforehand.
