### ISSUE TITLE
Full paths are shown instead of file/folder names

### ISSUE THREAD

**Issue by archiif** [nvim-telescope/telescope-file-browser.nvim#167]
### Description

![image](https://user-images.githubusercontent.com/60074051/182034001-0e722f0a-72a2-4640-a446-058b1b2d8ec8.png)

### Neovim version

```markdown
NVIM v0.8.0-dev-739-ge59bc078d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az158-506

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Microsoft Windows [Version 10.0.19043.1826]

### Steps to reproduce

1. Open the file browser
2. Full file paths are shown instead of file/folder names

### Expected behavior

File/folder names are displayed in the file browser just like in the screenshots

### Actual behavior

Full file paths are shown instead of file/folder names

### Minimal config

```Lua
-- Yes, this bug can be reproduced with this bare-bones config
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
I suspect this is a Windows-related issue as I unfortunately cannot reproduce on Arch Linux. Are you somewhat familiar with lua and might be able to look at this yourself with guidance from my end?

**Comment by miversen33** [comment]
I have a windows 10 machine, I will get the listed version of neovim installed on it and see what I can reproduce.

**Comment by miversen33** [comment]
I am _not_ able to replicate this behavior with the provided configuration
![image](https://user-images.githubusercontent.com/2640668/182054909-6760aa4f-ac3c-414a-842b-162f91ee54e5.png)

Note, I am not able to get my hands on the specific nightly that @archiif used, my version is 
```
NVIM v0.8.0-dev-745-g7f4c50f8c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Running with `nvim-qt`
Windows specifications
```
Edition	Windows 11 Pro
Version	21H2
Installed on	‎2021-‎11-‎02
OS build	22000.832
Experience	Windows Feature Experience Pack 1000.22000.832.0
```

@archiif I dont really know what else to ask for here, but as I cannot reproduce your issue, I am guessing there is more to the process you are following/doing to achieve this?

To replicate what I have above, I opened `nvim-qt.exe`
Executed
`:lcd C:\Users\miver\`
And then
`:Telescope file_browser`

**Comment by archiif** [comment]
I investigated further and it seems that the bug *only* occurs when I launch nvim via [Git Bash](https://gitforwindows.org/). I'm not sure what's the cause.

I suspect that it might have something to do with the path separators? It's possible that when the program is run on Git Bash, it outputs forward slashes when printing paths.

But both forward and backslashes are valid path delimiters on Windows. I noticed that it uses `Path.path.sep` in the code, I'm not sure how it works since there doesn't seem to be any documentation, but maybe the library expects only backslashes on Windows paths.

**Comment by fdschmidt93** [comment]
Yeah, `plenary` detects the OS and then infers path separators from there (`\` for Windows, thus incompatible with `git bash`). Is there any chance to configure `git bash` to use Windows path separators?

Otherwise, I suppose this is more a `plenary` issue and nothing we could do (nor would I want to, I'm afraid) from within `telescope-file-browser.nvim`.

**Comment by archiif** [comment]
Both forward and backslashes *are* valid Windows path separators. To handle Windows paths correctly, you need to anticipate the possibility of both types of slashes existing in a single path (e.g. `C:/path\to/file`). It's a surprisingly common occurrence (not a specific Git Bash issue), and basically all Windows-supported tools I've used seem to handle this correctly.

I'm not sure if the problem is on plenary, because `os_sep` being set to a backslash by default on Windows seem reasonable to me (Python[1] does the same thing). I think the problem is using the sep to do file path manipulation on the path string directly. Could you use any of the higher-level APIs on plenary to manipulate the paths instead (if there are any)?

[1] From the Python docs for reference:
os.**sep**
The character used by the operating system to separate pathname components. This is '/' for POSIX and '\\' for Windows. Note that knowing this is not sufficient to be able to parse or concatenate pathnames — use [os.path.split()](https://docs.python.org/3/library/os.path.html#os.path.split) and [os.path.join()](https://docs.python.org/3/library/os.path.html#os.path.join) — but it is occasionally useful. Also available via [os.path](https://docs.python.org/3/library/os.path.html#module-os.path).

**Comment by miversen33** [comment]
I don't have the code in front of me (I'll check when I'm home this evening), but IIRC, Telescope File Browser does absolutely nothing with path management, instead letting plenary manage that. This means that if there are path problems, they are from plenary. Plenary is what powers basically all of this plugin, including determining the path separators based on the determined OS.

I'll peek into the code a bit tonight to 100% verify what I said, but given what I've seen from my own path shenanigans with Telescope File Browser, I'm relatively confident in it. 

A quick way to check is to open up neovim in your git-bash instance, and then create a plenary path object via the command mode, and inspect the associated path separator. I'll edit this to give an actual code example later (typing code on mobile is tough).

**Comment by fdschmidt93** [comment]
I've also looked at this. Basically, what probably fails for you in `git bash` should be something like this example:

To expand what @miversen33 said

This should pinpoint the problem

1. Cd to any folder with some text file
2. Open text file on level of that folder
3. Do 

```
:lua Path = require "plenary.path"
:lua print(Path:new(vim.api.nvim_buf_get_name(0)):make_relative(vim.loop.cwd()))
```

see malformed output rather than just filename.

We do that here 

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/c30fcb6214acf8538616e403e0f82a6430bf6801/lua/telescope/_extensions/file_browser/make_entry.lua#L130

which refers to

https://github.com/nvim-telescope/telescope.nvim/blob/b5833a682c511885887373aad76272ad70f7b3c2/lua/telescope/utils.lua#L248

which would require a plenary fix as suspected.

**Comment by archiif** [comment]
I ran your commands:
```
cd /tmp && touch test.txt
nvim test.txt
:lua Path = require "plenary.path"
:lua print(Path:new(vim.api.nvim_buf_get_name(0)):make_relative(vim.loop.cwd()))
```
And it seems that it correctly outputs `test.txt` as the result.

**Comment by fdschmidt93** [comment]
Please repeat in the folder of the screenshot. This should really be the only string processing affecting how paths are displayed.

**Comment by archiif** [comment]
``` 
$ cd ~/appdata/local/nvim/lua/custom
$ ls
chadrc.lua  init.lua  mappings.lua  plugins/
$ nvim chadrc.lua
:lua Path = require "plenary.path"
:lua print(Path:new(vim.api.nvim_buf_get_name(0)):make_relative(vim.loop.cwd()))
```
It correctly outputs `chadrc.lua`

I only skimmed the code, but do you think these lines contribute to the problem:
https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/c30fcb6214acf8538616e403e0f82a6430bf6801/lua/telescope/_extensions/file_browser/make_entry.lua#L122

I also searched this repository and it seems that it does several manipulations or parsing using `os_sep` which might cause the issue:
https://github.com/nvim-telescope/telescope-file-browser.nvim/search?q=os_sep

**Comment by fdschmidt93** [comment]
Nope, `cwdsubstr` only affects ordinal computation and not what is displayed. Not sure whether the ordinal is correct in your case, but it doesn't affect what you see.

What about

`:lua print(Path:new(vim.api.nvim_buf_get_name(0)):make_relative(vim.fn.expand(vim.loop.cwd()))`

**Comment by archiif** [comment]
The command still outputs `chadrc.lua` correctly.
Is there a function from this library that I can test instead?

**Comment by fdschmidt93** [comment]
Follow the code as referred to [here](https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/167#issuecomment-1201128882)

**Comment by archiif** [comment]
What should I put in the `opts` argument?

**Comment by fdschmidt93** [comment]
`opts = { cwd = vim.fn.expand(vim.loop.cwd()}` typically. `vim.loop.cwd` gets updated to the current folder in the file browser.

That said, I wont be attending to this issue for the time being any longer as I've spent quite some time on this already without being equipped to help, that is, having Neovim set up on Windows appropriately, which I won't invest time in.

**Comment by archiif** [comment]
Ok, I think you're right, it's a plenary issue:
`:lua print(Path:new("D:/path/test.file"):make_relative("D:/path"))` outputs `D:/path/test.file`
`:lua print(Path:new("D:\\path\\test.file"):make_relative("D:\\path"))` ouputs `path\test.file`
I'll make an issue there.

**Comment by r1d4nd3v** [comment]
In my case I had "path_display = { smart }" causing the issue.
Hope it can help!
