### ISSUE TITLE
An option to trash files instead of removing them

### ISSUE THREAD

**Issue by Paveloom** [nvim-telescope/telescope-file-browser.nvim#169]
**Is your feature request related to a problem? Please describe.**
I would like to put files in the trash instead of removing them.

**Describe the solution you'd like**
A generic way to override the `remove` action (so I can change it to the `trash` command).

**Describe alternatives you've considered**
A configuration flag.

**Comment by fdschmidt93** [comment]
I briefly looked into it and it's very OS-dependent as there is no `libuv` reference. Consequently, I wouldn't support this from `telescope-file-browser.nvim`.

You can very easily implement your own solution if you know a little bit of lua. Have a look at 

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/4272c52078cc457dfaabce6fa3545e7495651d04/lua/telescope/_extensions/file_browser/actions.lua#L283-L314

and then implement a function ala

```lua
require "telescope".setup {

}

```

**Comment by fdschmidt93** [comment]
If there is a clean proposal and PR to implement this, I'd very much consider it, but I'm generally quite happy with current scope of filesys operations of `telescope-file-browser.nvim`, especially considering how straightforward anyone can implement the original request themselves balanced with implementation and maintenance overhead, as I only use linux.

For the time being, closing.

**Comment by Paveloom** [comment]
Thanks for the hints. I just rewrote my config in Lua the other day, had no experience with overwriting Telescope actions.

There are also issues with duplicates and setting up original folders, so it's not as straightforward as just moving files. 

I ended up with the following implementation:

```lua
require("telescope").setup({
  extensions = {
    file_browser = {
      -- <...>
      mappings = {
        ["i"] = {
          -- Trash files instead of deleting them
          ["<A-d>"] = function(prompt_bufnr)
            local action_state = require("telescope.actions.state")
            local call = require("config.utils").call
            local fb_utils = require("telescope._extensions.file_browser.utils")
            -- Get the finder
            local current_picker = action_state.get_current_picker(prompt_bufnr)
            local finder = current_picker.finder
            -- Get the selections
            local selections = fb_utils.get_selected_files(prompt_bufnr, false)
            if vim.tbl_isempty(selections) then
              fb_utils.notify("actions.trash",
                { msg = "No selection to be trashed!", level = "WARN", quiet = finder.quiet })
              return
            end
            -- Trash the selected files
            local trashed = {}
            for _, selection in ipairs(selections) do
              local filename = selection.filename:sub(#selection:parent().filename + 2)
              -- `trash-put` is from the `trash-cli` package
              if call({ "trash-put", "--", selection:absolute() }) then
                table.insert(trashed, filename)
              end
            end
            -- Notify about operations
            local message = ""
            if not vim.tbl_isempty(trashed) then
              message = message .. "Trashed: " .. table.concat(trashed, ", ")
            end
            fb_utils.notify("actions.trash", { msg = message, level = "INFO", quiet = finder.quiet })
            -- Reset multi selection
            current_picker:refresh(current_picker.finder, { reset_prompt = true })
          end,
        }
      }
    },
  }
})
-- <...>
```

where `require("config.utils").call` is

```lua
-- Do a system call and check the status code
function call(cmd)
    fn.system(cmd)
    return vim.v.shell_error == 0
end
```

**Comment by fdschmidt93** [comment]
I'm very glad to hear you've managed to whip up a solution! :)
