### ISSUE TITLE
request: input callbacks to move to $home and cwd

### ISSUE THREAD

**Issue by fdschmidt93** [nvim-telescope/telescope-file-browser.nvim#17]
As brought up by @skebanga on the telescope-gitter

> I would like to suggest an enhancement to telescope-file-browser. Namely, that if the user types ~/, the cwd is changed to ${HOME}; similarly, if the user types / the cwd is changed to root, Perhaps these could/should be controlled behind some options. I'm happy to take on the work to add this, but was hoping you'd give me a pointer as to where to start? The primary issue I see is that it's not a keybinding per-se, it's more like upon a keypress in insert mode, if the current path matches regex"^\/$"then change to root and refresh, or if the current path matches regex "^\~\/$" then change to ${HOME}. Do you think this would be possible?

**Comment by fdschmidt93** [comment]
The relevant segment to look at would be here:

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/2f2cd47a2bd4b299ef50db30301f5276cc319e4a/lua/telescope/_extensions/file_browser.lua#L87-L98

which goes to show that there already is an input callback to trigger the folder browser.

> similarly, if the user types / the cwd is changed to root

Your approach to input callbacks conflicts with the currently undocumented default that `/` triggers the folder browser right now. Note that there is also an action (only merged just now :) for this in `<C-w>/w`

>  if the user types ~/, the cwd is changed to ${HOME}

I think that's an interesting idea.

What do you think of making these available as input callbacks only in folder browser mode? I'm not sure, I kind of have to think about what the most ergonomic approach here is.

**Comment by skebanga** [comment]
Thanks for creating this issue! 

Let me play around with the current functionality and I'll come back with some comments

**Comment by skebanga** [comment]
I've created a PR [here](https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/20) - marked as draft so you can comment on the approach I took

It takes effect in both file and folder browser mode.

As a consequence I removed the `/` toggle to folder browser mode. Since it's already available in `C-f` I thought it would be acceptable?

**Comment by fdschmidt93** [comment]
Closing this as we've since agreed this should rather be a config recipe than global default.
