### ISSUE TITLE
cannot browse homedir files or folders on freebsd when fd is installed

### ISSUE THREAD

**Issue by pureume** [nvim-telescope/telescope-file-browser.nvim#170]
### Description

Files and folders anywhere in my home directory are not shown in the file/folder browser. This behavior is specific to my homedir. It is possible to navigate the root filesystem, for example, using file_browser as usual, but no folders or files are shown in telescope if called anywhere in my homedir or a subdirectory of it.

This only happens on my FreeBSD system when I have fd installed. Removing fd fixes the problem, and this problem does not occur on any of my Linux system (with or without fd installed).

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -pipe -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wno-c11-extensions -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/wrkdirs/usr/ports/editors/neovim/work/.build/config -I/wrkdirs/usr/ports/editors/neovim/work/neovim-0.7.2/src -I/usr/local/include -I/usr/include -I/wrkdirs/usr/ports/editors/neovim/work/.build/src/nvim/auto -I/wrkdirs/usr/ports/editors/neovim/work/.build/include
Compiled by root@130amd64-quarterly-job-02

Features: +acl +iconv +tui
```

### Operating system and version

FreeBSD 13.1-RELEASE

### Steps to reproduce

1. Navigate to $HOME or any subdirectory of it
2. Start nvim with the minimal config: (something like `nvim -nu minimal.lua`)
3 `:Telescope file_browser`

### Expected behavior

Ordinarily, the files and folders in the current directory are shown and may be opened or navigated.

### Actual behavior

No files or folders are shown except for `../`. Only when file_browser is called from a location outside of $HOME does it show any files or folders.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Apologies, I'm a bit out of my depth here as I have never used BSD or any distributions thereof. A brief search on Github issues of `fd` and broader google search did not yield any results.

The one solution I could think if is making opting out of `fd` configurable, though generally of course it would be great to understand what's causing your problem to fix it.

What does 

```lua
:lua vim.pretty_print(require "telescope.actions.state".get_current_picker(vim.api.nvim_get_current_buf()).finder._finder.results)
```

look like for you when launched when the file browser is opened in your home folder?

**Comment by pureume** [comment]
Output of the following command with file browser open in homedir: `:lua vim.pretty_print(require "telescope.actions.state".get_current_picker(vim.api.nvim_get_current_buf()).finder._finder.results)`

```lua
{ { "/usr/home",
    Path = {
      _cwd = "/usr/home/pureume",
      _sep = "/",
      filename = "/usr/home",
      <metatable> = {
        __concat = <function 1>,
        __div = <function 2>,
        __index = <function 3>,
        __tostring = <function 4>,
        _fs_filename = <function 5>,
        _read = <function 6>,
        _read_async = <function 7>,
        _split = <function 8>,
        _st_mode = <function 9>,
        _stat = <function 10>,
        absolute = <function 11>,
        close = <function 12>,
        copy = <function 13>,
        exists = <function 14>,
        expand = <function 15>,
        head = <function 16>,
        is_absolute = <function 17>,
        is_dir = <function 18>,
        is_file = <function 19>,
        is_path = <function 20>,
        iter = <function 21>,
        joinpath = <function 22>,
        make_relative = <function 23>,
        mkdir = <function 24>,
        new = <function 25>,
        normalize = <function 26>,
        open = <function 27>,
        parent = <function 28>,
        parents = <function 29>,
        path = {
          S_IF = {
            DIR = 16384,
            REG = 32768
          },
          home = "/home/pureume",
          root = <function 30>,
          sep = "/"
        },
        read = <function 31>,
        readbyterange = <function 32>,
        readlines = <function 33>,
        rename = <function 34>,
        rm = <function 35>,
        rmdir = <function 36>,
        shorten = <function 37>,
        tail = <function 38>,
        touch = <function 39>,
        write = <function 40>
      }
    },
    ordinal = "..",
    stat = {
      atime = {
        nsec = 985295000,
        sec = 1659961520
      },
      birthtime = {
        nsec = 985295000,
        sec = 1659961520
      },
      blksize = 4096,
      blocks = 1,
      ctime = {
        nsec = 112789000,
        sec = 1659962437
      },
      dev = -2.1500489532239e+18,
      flags = 2048,
      gen = 0,
      gid = 0,
      ino = 34,
      mode = 16877,
      mtime = {
        nsec = 112789000,
        sec = 1659962437
      },
      nlink = 3,
      rdev = -1,
      size = 3,
      type = "directory",
      uid = 0
    },
    <metatable> = {
      __index = <function 41>,
      cwd = "/usr/home/pureume",
      display = <function 42>
    }
  } }
```

**Comment by fdschmidt93** [comment]
Ok, that basically means the `async_oneshot_finder` is not appropriately populated with results from `fd` for you.

It's not quite the same, but does 

```lua
:lua vim.pretty_print(require "plenary.job":new({ command = "fd", args = { "-t=f" } }):sync())
```
work for you and show you the list of files when launched from `~`?

telescope actually uses a custom async linespipe, but let's try to diagnose a bit more simpler first.

**Comment by pureume** [comment]
It doesn't work, it just returns: `{}  0`. It also doesn't work when run in a place outside of `~/` that file_browser succeeds in showing files and folders, such as in `/usr/local`. It throws this error:

```
E5108: Error executing lua .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:499:
'fd -t=f' was unable to complete in 5000 ms
stack traceback:
        [C]: in function 'error'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:499: in function 'wait'
        .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:453: in function 'sync'
        [string ":lua"]:1: in main chunk
```

Thanks again for your help :)

**Comment by fdschmidt93** [comment]
Ah, sorry, my bad. The problem here is it runs `fd` on your entire home directory. Pick a folder with say ~10 files or something which you can look at easily in a few lines :sweat_smile:

**Comment by pureume** [comment]
In a subdir of `$HOME` with just a dozen or so files, the output of that command is exactly the same: `{}   0`.

**Comment by fdschmidt93** [comment]
Ok, just to make sure, if it's super easy for you, also run the same command on a linux distro, but it should show all absolute paths for files/folders in the folder and 0.

Does `:Telescope find_files` work for you on FreeBSD?

Sorry for the rodeo, but this will take a bit to pin down from afar :sweat_smile:

**Comment by pureume** [comment]
> Sorry for the rodeo, but this will take a bit to pin down from afar

No problem at all. It's the least I can do to show gratitude for this wonderful tool.

So I have tried running that command on some Linux machines and made an interesting discovery: that this problem occurs on Linux, but only in the top level of `$HOME`. I will try to summarize all the relevant details below.

The command you asked me to run (`:lua vim.pretty_print(require "plenary.job":new({ command = "fd", args = { "-t=f" } }):sync())`) I will refer to below as `plenary_fd_call`.

## FreeBSD

* **find_files**: works everywhere *except* `$HOME` and its subdirs
* **file_browser**: same behavior as find_files
* **plenary_fd_call**: works only outside of `$HOME`, and only in directories that are not too large/deep (it times out if run from `/`)
* **fd**: calling `fd` from the command line by itself (without arguments) returns results only outside of `$HOME` (and does not time out when called from the top level of `/`).  When it "fails" in $HOME the exit status is 0 (there is no error).

## Linux (Debain Bullseye, amd64, nvim 0.7 appimage)

* **find_files**: works everywhere *except* the top level of `$HOME` (works inside subdirs of `$HOME` and anywhere in `/`)
* **file_browser**: same behavior as find_files
* **plenary_fd_call**: same as find_files and file_browser, except that it times out if run from `/`.
* **fd**: calling `fd` by itself on the command line (without arguments) returns results everywhere except the top level of `$HOME`. When it fails in`$HOME` the exit status is 0 (no error).

## Summary

On FreeBSD, fd, file_browser, and find_files only work outside of `$HOME`, while on Debian they work everywhere, including subdirs of `$HOME`, but not in the top level of `$HOME` itself.

I hope this helps. Let me know if anything is unclear or if there's anything else I can do to debug this. Thanks again for your help :)

**Comment by fdschmidt93** [comment]
> that this problem occurs on Linux, but only in the top level of $HOME.

Do you have any configuration (`.gitignore`, `.fdignore` or something with user read rights -- some "brute force" ideas) or something that may prohibit that? Simple `fd` (`fd --version  == 8.4.0`) on my arch linux machine on `$HOME` attempts to stdout all files/folders (wall of text). Seems quuite odd.

> plenary_fd_call: works only outside of $HOME, and only in directories that are not too large/deep (it times out if run from /)

When you say works, does it give you the absolute paths now? Seems to conflict with earlier observation that

> In a subdir of $HOME with just a dozen or so files, the output of that command is exactly the same: {} 0.

since there should be paths in the first table.

Side note: `plenary_fd_call` in the sync version by default times out after 5 seconds, so timeout in `/` is expected.

I'm a bit puzzled, I don't think `telescope-file-browser.nvim` is per se the problem, but maybe more `fd` itself? If it works outside in system folders, then at least the job launcher and passthrough to `telescope` _can_ work as expected? This makes me think it might be worth opening an issue over at `fd`'s repo? Thoughts?

Potential workarounds for the time being:

- Remove `fd` as there doesn't seem to any utility on FreeBSD (telescope find_files falls back to `rg`, file-browser back to `plenary`)
- Use an option that forces file-browser to use plenary, like `{ grouped = true }`

**Comment by pureume** [comment]
> Do you have any configuration (.gitignore, .fdignore or something with user read rights -- some "brute force" ideas) or something that may prohibit that?

This was it >_< I manage dotfiles by making $HOME a git repo that ignores all contents except those added manually via `git add -f`. The places where it was working in subdirs of $HOME were other git repos, and the directories I made for testing purposes ultimately could not work because they were ignored by the .gitignore in the $HOME root. 

Sorry to have wasted your time with this, but I really appreciate all your help and time.

For anyone else who manages their dotfiles this way, a simple work around is to alias fd with some flags, such as `fd -I` to allow ignored files, or `fd -uu` to allow ignored and hidden files.

**Comment by fdschmidt93** [comment]
No worries, glad we managed to solve it :)
