### ISSUE TITLE
Use the "<cr>" behavior when pressing "o"

### ISSUE THREAD

**Issue by kunchenguid** [nvim-telescope/telescope-file-browser.nvim#172]
**Is your feature request related to a problem? Please describe.**
In the picker, I'd like to make "o" behave the same way as "\<cr\>" but it's not clear how to do so. I can't find an action that associates with the \<cr\> behavior. 

**Describe the solution you'd like**
Turn the \<cr\> behavior into one of the regular fb_actions that can be mapped to any key I like.

**Comment by fdschmidt93** [comment]
```lua
require "telescope".setup {
  extensions = {
    file_browser = {
      mappings = {
        ["n"] = {
          ["o"] = require "telescope.actions".select_default,
        }
      }
    },
  }
}
```
should be what you are looking for.

**Comment by fdschmidt93** [comment]
Ah apologies, I've closed this accidentally. Should be solved now though, let me know in case something's not working :)

**Comment by kunchenguid** [comment]
Thank you!
