### ISSUE TITLE
Allow changing `cwd` with `tcd` instead of `cd`

### ISSUE THREAD

**Issue by emi2k01** [nvim-telescope/telescope-file-browser.nvim#175]
**Is your feature request related to a problem? Please describe.**
I want to be able to change the current directory only for the current tab and not for the whole workspace.

**Describe the solution you'd like**
Add a setting to use `tcd` instead of `cd`.
I'm not sure how the solution would work as there's also `lcd` but that one is less useful.

**Describe alternatives you've considered**
fork and change this: https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/c30fcb6214acf8538616e403e0f82a6430bf6801/lua/telescope/_extensions/file_browser/actions.lua#L564

**Comment by emi2k01** [comment]
nvm, I just copied and pasted the function and created my own mapping with `tcd` instead of `cd`. I still think it'd be a good idea to have this in the plugin itself.

**Comment by jamestrew** [comment]
I think this comes down to personal preference so it's probably best for individual to tweak actions like you've already done.
