### ISSUE TITLE
Sort all the folders first than files

### ISSUE THREAD

**Issue by talis-fb** [nvim-telescope/telescope-file-browser.nvim#178]
**Is your feature request related to a problem? Please describe.**
Normally, when I'm navigating in folders I want to do one of two things: go to a folder or open a file. For me it is messy to have the two things together in Picker list. Being handle in same way.

**Describe the solution you'd like**
The picker list could (should) include all folders first, followed by the files. Like the navigation with **ranger** for example. Natively.

**Describe alternatives you've considered**
It'd be cool to have an option to set in setup, like `show_folders_first`. It wouldn't overwrite default behavior and make this feature optional.

I don't know if there is a specific setup to make this up. Anyway, it'd be nice to have it out-of-the-box.

### Example:
The picker list (in left) should be equal to the File list in the Preview (right). All the folders, followed by the sorted files.
![issue1](https://user-images.githubusercontent.com/54823205/189782436-cca1ddbd-0d49-4479-bed2-a870b72e74fa.png)

**Comment by fdschmidt93** [comment]
`:h telescope-file-browser.picker` points to `grouped`
vimscript
```viml
:Telescope file_browser grouped=true
```
lua
```lua
:lua require "telescope".extensions.file_browser.file_browser { grouped = true }
```
