### ISSUE TITLE
`nvim .` does not open file-browser

### ISSUE THREAD

**Issue by qRoC** [nvim-telescope/telescope-file-browser.nvim#182]
### Description

After https://github.com/nvim-telescope/telescope-file-browser.nvim/commit/c46e7e7e8adb9f17462d9ff1787209b483a640aa

`nvim .` does not open file-browser.

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
```

Fix this issue

### Neovim version

```markdown
NVIM v0.8.0-dev-1132-g37a71d1f2-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

MacOS 12.6

### Steps to reproduce

`nvim .`

### Expected behavior

Opens `file-browser`

### Actual behavior

Opens `netrw`

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Please provide a minimal init lua config. The one we provide is suboptimal here, since it may load in deferred fashion.

Make sure

- `hijack_netrw = true` in your config
- no lazy loading - both `telescope` and `telescope-file-browser.nvim` need to be active on start up

**Comment by qRoC** [comment]
> `hijack_netrw = true` in your config

```lua
telescope.setup {
  extensions = {
    file_browser = {
      hijack_netrw = true,
    },
  },
}

telescope.load_extension "file_browser"
```

> no lazy loading - both `telescope` and `telescope-file-browser.nvim` need to be active on start up

```lua
    use {
      "lewis6991/impatient.nvim",
      config = "require('impatient')",
    }

    -- package manager
    use { "wbthomason/packer.nvim" }

    -- lua functions
    use { "nvim-lua/plenary.nvim" }

    -- file type icons
    use {
      "kyazdani42/nvim-web-devicons",
      config = config "web-devicons",
    }

    -- treesitter
    use {
      "nvim-treesitter/nvim-treesitter",
      config = config "treesitter",
    }

    -- fuzzy finder
    use { "nvim-telescope/telescope-fzf-native.nvim", run = "make" }
    use { "nvim-telescope/telescope-file-browser.nvim" }
    use {
      "nvim-telescope/telescope.nvim",
      branch = "0.1.x",
      config = config "telescope",
      after = {
        "plenary.nvim",
        "nvim-web-devicons",
        "nvim-treesitter",
        "telescope-fzf-native.nvim",
        "telescope-file-browser.nvim",
      },
    }
```

**Comment by fdschmidt93** [comment]
I'm wondering whether this is an upstream (= `neovim` issue).

What happens in my minimal vs actual config

- `minimal`: 1. load user config, override non-existing `FileExplorer` autocmd, 2. load standard vimrc `FileExplorer` wrongfully gets overridden by `sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim`
- my config: vice versa of `minimal`
 
How are the files ranked if you do `nvim --startuptime log & nvim log.txt`

Do you see something like

019.205  000.264  000.264: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim

*below* the lua file that sources the `telescope-file-browser.nvim` configuration? Below meaning it's effectively sourced thereafter.

**Comment by fdschmidt93** [comment]
The upper block is loading the plugin, but not the configuration that invokes `hijack_netrw = true`.

When's the lua file that 
```lua
      config = config "telescope",
```
refers to sourced?

**Comment by qRoC** [comment]
```
173.327  006.900  000.744: require('plugins.telescope')
```
