### ISSUE TITLE
not displayed icons in file browser

### ISSUE THREAD

**Issue by mr-scrpt** [nvim-telescope/telescope-file-browser.nvim#184]
### Description

Hi. Icons are not displayed
![image](https://user-images.githubusercontent.com/48452376/192613854-b7505088-580b-45b0-ae99-63335b3d74b9.png)

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 20.04.5 LTS

### Steps to reproduce

open telescope-file-browser

### Expected behavior

see the icon

### Actual behavior

not see the icon

### Minimal config

```Lua
lua << EOF

  require('telescope').setup{ 
    defaults = { 
      file_ignore_patterns = {"node_modules"}
    },
    extensions = {
      file_browser = {
        theme = "ivy",
        -- disables netrw and use telescope-file-browser in its place
        hijack_netrw = true,
       
      },
    }
  }

  require("telescope").load_extension("file_browser")
  require('telescope').load_extension('fzf')
 
EOF
```

**Comment by fdschmidt93** [comment]
Needs https://github.com/kyazdani42/nvim-web-devicons as per https://github.com/nvim-telescope/telescope.nvim/#optional-dependencies

**Comment by mr-scrpt** [comment]
> Needs https://github.com/kyazdani42/nvim-web-devicons as per https://github.com/nvim-telescope/telescope.nvim/#optional-dependencies

Thank you for your response. I installed the nvim-web-devicons plugin and now it looks like this:


![image](https://user-images.githubusercontent.com/48452376/192730028-4f021c2c-657c-4811-8ac0-e1fe90000931.png)

**Comment by fdschmidt93** [comment]
Please read nvim-web-devicons installation instructions carefully. You 99% don't have a patched font.

**Comment by mr-scrpt** [comment]
> Please read nvim-web-devicons installation instructions carefully. You 99% don't have a patched font.

Thank you! It works
