### ISSUE TITLE
How to select and move files?

### ISSUE THREAD

**Issue by adonespitogo** [nvim-telescope/telescope-file-browser.nvim#185]
Hi, I'm new to neovim. In the readme about moving files, it says:

```
Move multi-selected files to path (file_browser) or selected directory (folder_browser)
```
How do I actually (multi) select files?
What are the key bindings for selecting files/directories?

**Comment by jamestrew** [comment]
You can multi-select with `<Tab>` & `<S-Tab>` (Shift+Tab) and then navigate to where you want to move them to, then press `<A-m>` (Alt + m) in insert mode or just `m` in normal mode. 

You can use telescope's builtin `which_key` (insert mode: `<C-/>`, normal mode: `?`) to see keymaps for any give telescope picker.

**Comment by fdschmidt93** [comment]
Thanks @jamestrew - I think this is sufficiently answered. For a visual reference as to what was described, please refer to the [media issue](https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/53#issuecomment-1010301465).

**Comment by vando026** [comment]
It would be very helpful if multi-selection using <Tab> or <S-Tab> is explicitly mentioned in the README of this repo. It is only when I searched manually through the closed issues that I discovered this page and learned how to multi select and move. Just a suggestion for new future users of this plugin (which I have chosen to replace NERDTree of many years of use).

**Comment by jamestrew** [comment]
Yeah I agree. I can cook something up tomorrow (~12 hrs) if nobody gets to it by then.
