### ISSUE TITLE
Add action to copy file name and/or path as string

### ISSUE THREAD

**Issue by benfrain** [nvim-telescope/telescope-file-browser.nvim#191]
I often use this plugin to find an asset in my project I wish to subsequently insert as text into code.

**Describe the solution you'd like**
An action than yanks the currently selected file name and/or path as text to the buffer

**Describe alternatives you've considered**
Currently I either try and remember what I see (memory not great, many mistakes happen :)), or open the file and then get the filename of the buffer.

**Comment by fdschmidt93** [comment]
I wouldn't have those in `telescope-file-browser.nvim`, but you could easily adapt `telescope.actions` to your own liking.

https://github.com/nvim-telescope/telescope.nvim/blob/f174a0367b4fc7cb17710d867e25ea792311c418/lua/telescope/actions/init.lua#L480-L497

In both cases you'd need

```lua
local symbol = action_state.get_selected_entry().value
```
rather than `value[1]`.

In any case, it's probably more of an upstream (= `telescope`) issue to generalize that function if you wouldn't be happy to adapt those issues.

Hope it helps, if there's any more `telescope-file-browser.nvim`-specific questions, happy to answer here. Otherwise, closing for the time being.

**Comment by benfrain** [comment]
Thanks @fdschmidt93 – for any future travellers I was able to run with the selection and add two new functions. One adds just the filename, and the other the filename and path (there is a whole bunch of stuff in `vim.inspect(action_state.get_selected_entry())`!

```lua
--- Insert filename into the current buffer and keeping the insert mode.
actions.insert_name_i = function(prompt_bufnr)
  local symbol = action_state.get_selected_entry().ordinal
  actions.close(prompt_bufnr)
  vim.schedule(function()
    vim.cmd([[startinsert]])
    vim.api.nvim_put({ symbol }, "", true, true)
  end)
end

--- Insert file path and name into the current buffer and keeping the insert mode.
actions.insert_name_and_path_i = function(prompt_bufnr)
  local symbol = action_state.get_selected_entry().value
  actions.close(prompt_bufnr)
  vim.schedule(function()
    vim.cmd([[startinsert]])
    vim.api.nvim_put({ symbol }, "", true, true)
  end)
end

require("telescope").setup({
  defaults = {
    sorting_strategy = "descending",
    prompt_prefix = "   ",
    winblend = 25,
    mappings = {
      i = {
        ["<esc>"] = actions.close,
        ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
      },
    },
  },
  extensions = {
    file_browser = {
      theme = "ivy",
      hidden = true,
      mappings = {
        ["i"] = {
          ["<S-M>"] = fb_actions.move,
          ["<C-Y>"] = actions.insert_name_i,
          ["<C-P>"] = actions.insert_name_and_path_i,
        },
      },
    },
  },

```

**Comment by jolars** [comment]
> I wouldn't have those in telescope-file-browser.nvim, but you could easily adapt telescope.actions to your own liking.

Really? It seems like a very fitting functionality for telescope-file-browser to me.
