### ISSUE TITLE
Sorting file and folder in file browser

### ISSUE THREAD

**Issue by mr-scrpt** [nvim-telescope/telescope-file-browser.nvim#192]
Hi. Is there any way to sort files and folders so that folders are always at the top and files at the bottom, like in Midnight Commander or TotalCommander?
![image](https://user-images.githubusercontent.com/48452376/196967605-61048817-ca4c-43eb-a0db-5b9afec04b0a.png)

**Comment by jamestrew** [comment]
You can do so by settings `grouped = true` in the telescope settings. 
```lua
require("telescope").setup({
  extensions = {
    file_browser = {
      -- your settings...
      grouped = true,
    },
  },
})
```
Doing this makes the file browser use plenary's `scandir` functionality over `fd` so it's will be slower. Personally, it's not a noticeable difference.

**Comment by fdschmidt93** [comment]
Thanks @jamestrew :)

Closing unless there's further questions. For future reference, the documentation for these options is available at `:h telescope-file-browser.picker`.

One further note -

> Doing this makes the file browser use plenary's scandir functionality over fd so it's will be slower. Personally, it's not a noticeable difference.

This would primarily become relevant in very, very large directories or setting `depth` (depth of folder levels to browse) to a large value.
