### ISSUE TITLE
`cwd_to_path = true` does not produce expected behavior

### ISSUE THREAD

**Issue by rhythm16** [nvim-telescope/telescope-file-browser.nvim#195]
### Description

Hello, I set `cwd_to_path = true`, when I navigate to another folder using `file_browser` and toggle back to `folder_browser`, I still see the subfolders in the original folder instead of the current folder in `file_browser`.
I have my directory layout like this:
```
somecode/
├── a/
│   └── aa/
├── b/
    └── bb/
```

### Neovim version

```markdown
NVIM v0.8.0-26-g7a011cb58
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

ubuntu 22.04

### Steps to reproduce

Using the directory layout in the description:
1. start `nvim` in `somecode/a` (`cwd`)
2. `:Telescope file_browser`
3. use `file_browser` to navigate to parent (`somecode`) and then enter `b/`
4. toggle to `folder_browser`

### Expected behavior

After step 4, I expect to see `b/` and `bb/`.

### Actual behavior

I see `a/` and `aa/`, although the path showing on top of the left plane has changed to `somecode/b/`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup {
    extensions = {
      file_browser = {
        cwd_to_path = true,
      },
    },
  }
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Didn't want to create any confusion but I'm not able to reproduce this behavior using the minimal config and outlined instructions (including directory structure).

I'm not even certain your expected behavior is correct. Maybe I'm misinterpreting the steps but once you navigate to `b/`, that becomes your cwd so toggling `folder_browser` should only show directories within `b/` which in this case is `bb/` and that is what I'm getting.

I'm running neovim nightly `3098064f3`.

**Comment by rhythm16** [comment]
Thanks for helping, here is a screen recording to clarify:

https://user-images.githubusercontent.com/31589689/204700601-b839e1fd-a1c5-44a3-89a3-9567a172ce57.mp4

My understanding is that after I enter `b/` (around 0:12-0:13 in the recording), I should see the subdirectories under `b/`, not `aa/` when I toggle to `folder_browser` (I toggled a few times near the end of the recording).
Is that correct?

**Comment by jamestrew** [comment]
Correct, you shouldn't be seeing `aa/` using `folder_browser` with `cwd_to_path` with `somecode/b/`. So there's definitely something going on here.

Can you try the exact same thing with `nvim --clean -u minimal_init.lua` (where `minimal_init.lua` is the minimal config you posted above)?

**Comment by rhythm16** [comment]
The behavior is the same except for this error message:
![Screenshot](https://user-images.githubusercontent.com/31589689/204705386-479aaf03-aeff-4353-b5f3-97c6b39c0b68.png)
Sorry for not finding this earlier, error didn't show the last time I tried without `--clean`

The code around the error:
file: `/tmp/nvim/site/pack/packer/start/packer.nvim/lua/packer/plugin_utils.lua`
```
  75   │ plugin_utils.update_helptags = vim.schedule_wrap(function(...)
  76   │   for _, dir in ipairs(...) do
  77   │     local doc_dir = util.join_paths(dir, 'doc')
  78   │     if plugin_utils.helptags_stale(doc_dir) then
  79   │       log.info('Updating helptags for ' .. doc_dir)
  80   │       vim.cmd('silent! helptags ' .. vim.fn.fnameescape(doc_dir))
  81   │     end
  82   │   end
  83   │ end)
  84   │ 
  85   │ plugin_utils.update_rplugins = vim.schedule_wrap(function()
  86   │   if vim.fn.exists ':UpdateRemotePlugins' == 2 then
  87   │     vim.cmd [[silent UpdateRemotePlugins]]
  88   │   end
  89   │ end)
  90   │ 
  91   │ plugin_utils.ensure_dirs = function()
  92   │   if vim.fn.isdirectory(config.opt_dir) == 0 then
  93   │     vim.fn.mkdir(config.opt_dir, 'p')
  94   │   end
  95   │ 
  96   │   if vim.fn.isdirectory(config.start_dir) == 0 then
  97   │     vim.fn.mkdir(config.start_dir, 'p')
  98   │   end
  99   │ end
```
Does this mean the misbehavior may be from `packer`?

**Comment by jamestrew** [comment]
I don't think that error matters. I get that with `--clean` as well and I still can't reproduce it. I tried on nvim v0.8.0 as well and I still can't reproduce it. Very strange...

**Comment by rhythm16** [comment]
I tried using docker and the problem still persists:
1. `sudo docker run -it ubuntu bash`
2. run: 
```
apt update
apt install -y wget
apt install -y git
wget https://github.com/neovim/neovim/releases/download/v0.8.0/nvim-linux64.tar.gz
tar xzvf nvim-linux64.tar.gz
mkdir -p /tmp/a/aa /tmp/b/bb
```
3. `/nvim-linux64/bin/nvim /tmp/min.lua` and paste in the minimal config
4. `cd /tmp/a`
5. `/nvim-linux64/bin/nvim --clean -u /tmp/min.lua` and wait for it to install plugins
6. restart `/nvim-linux64/bin/nvim --clean -u /tmp/min.lua` and do the steps to reproduce

I have tested on two machines now:
bug: seeing `aa/` after entering `b/`
no bug: seeing `bb/` after entering `b/`
|   |navtive|docker|
|---|---|---|
|machine A|bug (my original case)|bug|
|machine B|no bug (your case)|bug|

**Comment by fdschmidt93** [comment]
Do you still run into the error on docker?

I cannot reproduce when plugging in `cwd_to_path = true` in my config.

Are you doing `require('telescope').load_extension('file_browser')` after telescope config? Otherwise the config is not loaded appropriately.

**Comment by rhythm16** [comment]
If your error means seeing `aa/` after entering `b/`, then yes.
If you mean the error message from `plugin_utils.lua`, also yes.
Also yes, I am doing `require('telescope').load_extension('file_browser')` after telescope config, I tested with the minimal config listed above.

**Comment by rhythm16** [comment]
Here is me reproducing it using docker:

https://user-images.githubusercontent.com/31589689/204806051-0a6a69e1-1d4c-4886-baf8-a142ab4384ae.mp4

**Comment by fdschmidt93** [comment]
I've had issues with the minimal config and the way it loads.

Make sure that
1. Open telescope file browser
2. `:lua= TelescopeGlobalState[vim.api.nvim_get_current_buf()].picker.finder.cwd_to_path` prints `true` (while having file browser open)

Otherwise something with config loading is off. That you can also check with your config.

If that's the case we have a proper bug on our hands.

**Comment by rhythm16** [comment]
I can confirm it prints `true` and still doesn't work.
The environment is set up in docker with the steps written above.

https://user-images.githubusercontent.com/31589689/204813855-cbec44ee-f7f3-4cd7-9b32-fa60a813e21f.mp4

**Comment by fdschmidt93** [comment]
Ah, apologies. I've now made time to briefly look at the code and fixed a quite obvious bug. Please pull and test whether it also fixes your issue.

The problem was that `cwd_to_path` was only respected if `fd` was used. `fd` is generally very very highly recommended for `telescope-file-browser.nvim`.

**Comment by rhythm16** [comment]
Makes sense, I didn't have `fd` installed.
Issue fixed, and thank you for the amazing work!

**Comment by fdschmidt93** [comment]
Glad it got resolved, thank you for the support :)
