### ISSUE TITLE
Windows - `<C-o>` - Open file/folder with default system application causes errors

### ISSUE THREAD

**Issue by DasOhmoff** [nvim-telescope/telescope-file-browser.nvim#198]
### Description

Hello, thanks for this great plugin :)

When I try to open the current file or folder via `<C-o>`, then I get the following error message:
```lua
session.vim 2.13.1: Opened global 'angulart-test-project' session from ~\VimFiles\sessions\angulart-test-project.vim.
Do you need to configure your work environment as `luassert`?
E5108: Error executing lua ...\site\pack\packer\start\plenary.nvim/lua/plenary/job.lua:106: start: Executable not found
stack traceback:
	...\site\pack\packer\start\plenary.nvim/lua/plenary/job.lua:106: in function 'new'
	....nvim/lua/telescope/_extensions/file_browser/actions.lua:512: in function 'run_replace_or_original'
	...packer\start\telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...k\packer\start\telescope.nvim/lua/telescope/mappings.lua:341: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'error'
	...\site\pack\packer\start\plenary.nvim/lua/plenary/job.lua:106: in function 'new'
	....nvim/lua/telescope/_extensions/file_browser/actions.lua:512: in function 'run_replace_or_original'
	...packer\start\telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
	...k\packer\start\telescope.nvim/lua/telescope/mappings.lua:341: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
```

I am not sure what the issue might be, maybe it has something to do with the fact that I use windows.

Thanks for your help

### Neovim version

```markdown
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 10 - 64 bit

### Steps to reproduce

1. Open the file browser
2. Select any file
3. Use the `<c-o>` shortcut to the current file via a system application

### Expected behavior

The file should open via the default system application without any errors

### Actual behavior

Error get thrown

### Minimal config

```Lua
local telescope = require('telescope')
telescope.setup({})
telescope.load_extension('file_browser')
```

**Comment by fdschmidt93** [comment]
I'm currently travelling for my job. Could you please give me a friendly ping next week and I will look into this? Thanks :)

**Comment by DasOhmoff** [comment]
@fdschmidt93 Hello :) It is the next week now, here is the poing :)

**Comment by jamestrew** [comment]
Hey, I can take a look into this.
My initial impression is that this is Windows related. Since I don't have a Windows machine I can test off of you'll have to bare with me a little bit.

Can you open up command prompt and run `start .`? This should open up the File Explorer in the current path but from the looks of that error message, seems like `start` isn't an executable for you... which doesn't seem right.

**Comment by DasOhmoff** [comment]
Hello. I tested out `start .` with cmd but it seems to be working fine, it opens the file explorer in the current window.

**Comment by jamestrew** [comment]
Ok, I managed to do a little testing on a Windows machine. I believe the issue comes down to how shell built-ins aren't in the `$env:Path` on Windows for whatever reason.

Can you confirm `:echo executable('start')` returns `0` but `:!start .` works?

**Comment by DasOhmoff** [comment]
Yes, i tested it out and this is exactly what happens

**Comment by fdschmidt93** [comment]
> Ok, I managed to do a little testing on a Windows machine. I believe the issue comes down to how shell built-ins aren't in the $env:Path on Windows for whatever reason.

`plenary.jobs` won't also be able to pick up `start` then, because it has the same `$PATH` visibility as `nvim` itself. From what I can tell, @DasOhmoff will have to adjust `$PATH`s make `:echo executable('start')` to show `1` and then it just works. Unfortunately, I cannot test with Windows so I wouldn't know how to fix this.

**Comment by jamestrew** [comment]
That will probably be the best thing to do but looking into it a bit, I couldn't find any obvious way to do it.

A dirty fix might be to bind `<C-o>` to a custom open function. Something like this maybe?
```lua
local my_open = function(prompt_bufnr)
  local quiet = action_state.get_current_picker(prompt_bufnr).finder.quiet
  local selections = fb_utils.get_selected_files(prompt_bufnr, true)
  if vim.tbl_isempty(selections) then
    fb_utils.notify("actions.open", { msg = "No selection to be opened!", level = "INFO", quiet = quiet })
    return
  end

  for _, selection in ipairs(selections) do
    vim.cmd(string.format('silent !start "%s" &', selection:absolute()))
  end
  actions.close(prompt_bufnr)
end
```

**Comment by khanghy1000** [comment]
Here is my workaround:
`
local actions = require("telescope.actions")
require("telescope").setup {
  extensions = {
    file_browser = {
      mappings = {
        ["i"] = {
          ["<C-o>"] = actions.select_default
        },
        ["n"] = {
          ["o"] = actions.select_default
        },
      },
    }
  }
}
`

**Comment by JustBarnt** [comment]
@khanghy1000 Thank you for your workaround, this works perfectly and has been driving me crazy!
