### ISSUE TITLE
Option to disable fd usage

### ISSUE THREAD

**Issue by abrahamnm** [nvim-telescope/telescope-file-browser.nvim#212]
**Is your feature request related to a problem? Please describe.**
The file browser does not list files or directories on results when using an old version of fd (7.4.0), unfortunately I don't have the sudo permissions to upgrade fd because its a server.

**Describe the solution you'd like**
It would be great an option is added to disable fd utilization.

**Comment by gegoune** [comment]
You might want to install newer version locally and amend `PATH` accordingly. Would that be an option?

**Comment by fdschmidt93** [comment]
I'm okay with the flag, but YSK that `fd` will always be preferred (speed, functionality like gitignore, etc.). For instance, the `tree` view (#210)  will *only* be available with `fd` as it would be way too much work otherwise.

So the suggestion of @gegoune is what you ideally should be doing.

**Comment by abrahamnm** [comment]
Thanks @jamestrew!
Thanks @gegoune and @fdschmidt93 for the insight! I don't think I understand how to work on the suggestion of using a local version, but will look into that!

**Comment by gegoune** [comment]
You can just grab built release for your architecture and drop it to any directory on your server. You would then need ti add that directory at the start of PATH variable. Good luck. :)
