### ISSUE TITLE
NvimTreeFindFile equivalent for file-browser

### ISSUE THREAD

**Issue by shydefoo** [nvim-telescope/telescope-file-browser.nvim#223]
Hello,

Is there a similar feature to [|:NvimTreeFindFile|](https://github.com/nvim-tree/nvim-tree.lua/blob/e8a89db1bbc06510a76fc935754b4e99a3e5e8a7/doc/nvim-tree-lua.txt#L122)?

I was looking for some way to open the file browser using the current buf name as the path, or something similar. Tried checking the docs and issues but no luck. Thanks!

**Comment by jamestrew** [comment]
Using `:Telescope file_browser path=%:p:h` will open the file browser in the path of the current buffer. Does that match what you're looking for?

**Comment by shydefoo** [comment]
Somewhat, yes, but the file path of the current buffer is not highlighted. Thanks tho, this will do for now. Closing issue.

**Comment by gegoune** [comment]
Is it `select_buffer = true` you are after?

**Comment by jamestrew** [comment]
Good call, `:Telescope file_browser path=%:p:h select_buffer=true` should do.
