### ISSUE TITLE
independent `hidden` option for file/folder browser

### ISSUE THREAD

**Issue by jamestrew** [nvim-telescope/telescope-file-browser.nvim#227]
Leaving this mostly for myself as a reminder.

Currently the `hidden` option applies to both the file & folder browser. I'd like to have the ability to have something like `hidden = true` for the file browser but `hidden = false` for the folder browser.

I think turning the `hidden` option to be able to optionally take a table will be a fairly simple way to accommodate this. 
eg. `hidden = { file_browser = true, folder_browser = false }`.
With this, I'm leaning on changing the default to `hidden = { file_browser = false, folder_browser = false }`. This will preserve the default behavior but illustrate the capacity to differentiate the `hidden` option between the browsers.

**Comment by fdschmidt93** [comment]
> With this, I'm leaning on changing the default to hidden = { file_browser = false, folder_browser = false }

#210 has pretty much exactly this in broader scope (ie any option). Users will be able to define their own pickers. I just need the time and motivation to finish it 😅
