### ISSUE TITLE
Highlight group for directories

### ISSUE THREAD

**Issue by ivanbrennan** [nvim-telescope/telescope-file-browser.nvim#230]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to highlight directories differently from regular files in the results list, making it easier to distinguish between the two.

**Describe the solution you'd like**
A `dir_hl` config option, similar to the existing `dir_icon_hl` but applied to the directory name rather than to its icon.

**Describe alternatives you've considered**
The `dir_icon` allows you to display an icon beside each directory name, but I prefer no icons. I find it clutters the UI too much and leads to inconsistent alignment of directory names and regular file names.

**Additional context**
This first screenshot shows the [Dirvish](https://github.com/justinmk/vim-dirvish) plugin, which provides a highlight group specifically for directories:

<img src="https://user-images.githubusercontent.com/1672874/218279442-ba43c58c-62f6-40aa-b8cb-e68a5cca1ae9.png" width="500" />

This second screenshot shows telescope-file-browser, which does not provide a way to highlight directories differently from regular files:
<img src="https://user-images.githubusercontent.com/1672874/218279592-c774c3df-25b0-4694-8033-af9d05a0a8f5.png" width="500" />

**Comment by jamestrew** [comment]
I think this is a pretty solid idea - I can look into this.

Can you expand on this?
> leads to inconsistent alignment of directory names and regular file names.

I use icons and I don't have alignment issues but I'm curious if others do as that's something that ideally shouldn't be happening.

**Comment by ivanbrennan** [comment]
@jamestrew It looks like the alignment issue I was referring to is the same one you've already fixed in #217. I was using an older revision of this plugin, so it didn't have your fix.

I don't have nvim-web-devicons installed, so if `dir_icon` was non-empty, I was seeing this:

![image](https://user-images.githubusercontent.com/1672874/218286614-c9902fb7-0eb4-4fd4-8e2a-a1fe112a1086.png)
