### ISSUE TITLE
[telescope.run_command] : Unknown command

### ISSUE THREAD

**Issue by AyushSehrawat** [nvim-telescope/telescope-file-browser.nvim#235]
### Description

Initiating the file browser via the custom keybindings is giving the error of saying unknown command

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 22.10

### Steps to reproduce

1.) Add file-browser.lua in your plugins folder of nvim config
2.) Copy the following code

```
return {
  "nvim-telescope/telescope-file-browser.nvim",
  keys = {
    {
      "<leader>sB",
      ":Telescope file_browser path=%:p:h=%:p:h<cr>",
      desc = "Browse Files",
    },
    config = function()
      require("telescope").load_extension("file_browser")
    end,
  },
}
```

### Expected behavior

To open the file browser

### Actual behavior

Giving error while running the command

![image](https://user-images.githubusercontent.com/69469790/219881133-af97fe45-2d59-4bcb-b4f8-6c3959fc87fb.png)

### Minimal config

```Lua
// no minimal config provided
```

**Comment by AyushSehrawat** [comment]
I am sorry for not adding the minimal config, since i am not that good with neovim config and was using LazyVim. 
I added the config to ~/.config/nvim/lua/plugins folder

**Comment by AyushSehrawat** [comment]
Also mentioned in https://github.com/doom-neovim/doom-nvim/issues/357 with no response

**Comment by jamestrew** [comment]
I see several issues/potential issues with your config.
Main one being you missed a closing bracket for your `keys` table; so you `config` function is actually inside of `keys` and so it's not being called -> `file_browser` extension isn't being loaded.

But beyond that, just looking at your config file structure via `neo-tree`, I just want to confirm that you have all the dependencies for `telescope` and that you're calling the `setup` function (which I think you are).
Also, in the key mapping itself, I think you have an extra `=%:p:h` in there. Don't think it's an issue but yeah.

Here's a minimal config if you want to test/see for yourself. I can copy this into a directory in `/tmp` and start neovim using it with `nvim -nu min.lua`.
<details>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"nvim-telescope/telescope.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope-file-browser.nvim",
	},
	keys = {
		{
			"<leader>sB",
			":Telescope file_browser path=%:p:h<cr>",
			desc = "Browse Files",
		},
	},
	config = function()
		require("telescope").setup({})
		require("telescope").load_extension("file_browser")
	end,
}

vim.g.mapleader = " " -- change this to your preferred leader key
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("habamax")
```

</details>

**Comment by AyushSehrawat** [comment]
Thanks @jamestrew , after some modifies to the lua file from the minimal config you provided, it's working fine
