### ISSUE TITLE
Idea: Display the relative path closer to the search bar

### ISSUE THREAD

**Issue by robert-blankenship** [nvim-telescope/telescope-file-browser.nvim#238]
When you're exploring files with the *amazing* Telescope File Browser, your eyes are often drawn to the bottom of the screen, because that is where the text input and selector usually are.

As a user, I completely didn't realize that the relative path is shown above the middle content pane, for two reasons:
- It's shown in the same text and font as the titles for the other panes ("File Preview", "File Browser").

I literally didn't realize it until I started writing this feature request. I was about to ask "How cool would it be to see the relative path?" when I realized that it's there, but my monkey brain had a hard time seeing it 😀 

Here's what I was thinking for the layout:
- Show the relative path right over the search bar, in the color appropriate to directories.
- Add the filename for the selected file/folder to the bottom of the "File Preview" section, in the color appropriate to that file type.
- Just for fun, maybe show the Neovim working directory somewhere as well?

I will admit my naivety; it is probably this way for a reason. Maybe due to limitations of the Telescope framework?

**Comment by jamestrew** [comment]
Not quite what you're asking for but I would suggest maybe trying out the `ivy` theme and pass `vim.loop.cwd()` to the `prompt_title` option like so:
```lua
require("telescope").setup({
  extensions = {
    file_browser = {
      theme = "ivy",
      prompt_title = vim.loop.cwd(),
      -- other options
    },
  },
})
```
This shows you the current path a little closer to the prompt than the default telescope theme and also add the current working directory at the top.
![image](https://user-images.githubusercontent.com/66286082/219922534-c86d6948-933b-4268-b4dd-869dd736f94f.png)

Beyond this point, changing the layout to match what you're looking for would take a non-trivial amount of effort.

**Comment by robert-blankenship** [comment]
Okay, I will try the other theme. I do like the current theme though, it is pretty slick.

> non-trivial amount of effort.
No worries, feel free to close my issue. Thanks for taking the time to look at it.

To clarify, something like this:

![image](https://user-images.githubusercontent.com/7118222/219923491-457d2ca3-1917-4983-9ca8-4769324b4e8a.jpeg)

To me, a big use case of this plugin is moving, renaming and deleting files. So you want to know where you are in the tree. I think it deserves prime real estate in the view.

I pretty much only care about files in the CWD of `nvim`.

Also, are you aware of a way to change the ordering of columns in the "File Preview" when selecting a folder? Maybe showing the filenames in the leftmost column?

**Comment by gegoune** [comment]
@jamestrew 
> Not quite what you're asking for but I would suggest maybe trying out the ivy theme and pass vim.loop.cwd() to the prompt_title option like so:
I believe that only catches state of `cwd` at the time Telescope initialises? Changing directories (cwd) does not affect that title and `prompt_title` does not appear to be able to be a function.

**Comment by jamestrew** [comment]
@gegoune yeah you're right. `cd`ing around within nvim would create a discrepancy between the `prompt_title` and the actual `cwd`. Having a dynamic `prompt_title` would require some changes to the plugin.

@robert-blankenship we can certainly look into adding more flexibility in what the titles (border titles in red in your screenshot) display through exposing them as functions people can write themselves. Changing the location of them would probably mean creating a new theme/layout.

As for the "File Preview", unfortunately no easy way of changing how things are displayed. We're reusing the `file_previewer` from upstream telescope. You're not the first person to suggest a more flexible previewer. No promises but I can look into this.
