### ISSUE TITLE
Remove gap

### ISSUE THREAD

**Issue by mr-scrpt** [nvim-telescope/telescope-file-browser.nvim#240]
Hi all. Can you please tell me how I can remove this indentation
<img width="833" alt="image" src="https://user-images.githubusercontent.com/48452376/220155634-61c3a12d-e35f-49b7-b581-57c8c284166d.png">

**Comment by jamestrew** [comment]
Hey @kevinm6, could you please create a new issue using the bug report template? This will make it easier for me to identify the issue you're having and provide you with a solution.
