### ISSUE TITLE
Git status not displayed

### ISSUE THREAD

**Issue by kevinm6** [nvim-telescope/telescope-file-browser.nvim#243]
### Description

> Sorry @jamestrew, I can’t figure out how display `git_status`.
> 
> It is set to true in my config, I’ve checked the colorscheme for the [hi-groups used](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/6eb6bb45b7a9bed94a464a3e1dadfe870459628c/lua/telescope/_extensions/file_browser/git.lua#L57) and that gap is present but I don’t get any symbol present in the [git module](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/6eb6bb45b7a9bed94a464a3e1dadfe870459628c/lua/telescope/_extensions/file_browser/git.lua).
> 
> 
> 
> PS: `Telescope git_status` display default icons and hi-groups correctly.

As reported above in a previous comment, I can’t figure out how display `git_status` in `Telescope file_browser`

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
```

### Operating system and version

macOS 13.2.1 (22D68)

### Steps to reproduce

1. nvim
2. :Telescope file_browser git_status=true or everything else that call file browser

### Expected behavior

As reported on #222

### Actual behavior

<img width="958" alt="Screenshot 2023-02-24 at 23 32 14" src="https://user-images.githubusercontent.com/72861758/221307301-a5e770e5-de2f-48ec-97e2-8f0dd480054b.png">

### Minimal config

https://github.com/kevinm6/nvim/blob/fd63f2d3005ef74db1f0fab76aa9bc7f857f4af2/lua/plugins/core/telescope.lua#L440-L455

**Comment by jamestrew** [comment]
I've tried you settings and see the git status symbols.

In the directory you're showing, can you try `git status -s .`?
If that looks good, try the following - this is what I tried to reproduce.

<details>
<summary>min.lua</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{
		"nvim-telescope/telescope-file-browser.nvim",
		dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
		config = function()
			require("telescope").setup({
				extensions = {
					file_browser = {
						previewer = false,
						cwd = "%:p:h",
						initial_mode = "insert",
						select_buffer = true,
						hijack_netrw = true,
						layout_strategy = "bottom_pane",
						sorting_strategy = "ascending",
						hidden = false,
						git_status = true,
						color_devicons = true,
						use_less = true,
						layout_config = {
							prompt_position = "bottom",
							height = 0.5,
						},
					},
				},
			})
			require("telescope").load_extension("file_browser")
		end,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("habamax")
-- add anything else here

```

</details>

1. `mkdir -p /tmp/testing`
2. `cd /tmp/testing`
3. `git init`
4. `touch min.lua` and paste the contents of the `min.lua` above
5. `nvim -nu min.lua`
6. after plugins install and load, `:Telescope file_browser`
![image](https://user-images.githubusercontent.com/66286082/221325383-8526ffea-7005-4b3b-9972-bf8f2c371c0d.png)

I get the `?` git status symbol next to `min.lua`.

**Comment by kevinm6** [comment]
Nothing, I’ve already tried that and now again, but I get the same result.

<img width="755" alt="Screenshot 2023-02-25 at 09 56 14" src="https://user-images.githubusercontent.com/72861758/221348362-d68559d8-19fe-4dd6-8acf-56054377a42a.png">

- - - 

Output of `git status -s .`
```zsh
 git status -s  
   ?? .repro/
   ?? min.lua
```

At the beginning I was thinking that the culprit was the git directory instantiated with `git init —-separate-git-dir=<other_dir>` but I’ve check even in other dirs.

**Comment by jamestrew** [comment]
Are you getting leading white space in the `git status -s` output or is that just how you formatted/copy&pasted?

**Comment by kevinm6** [comment]
No leading spaces, sorry, I’ve formatted it.
This is what I get:

<img width="754" alt="Screenshot 2023-02-25 at 19 29 54" src="https://user-images.githubusercontent.com/72861758/221373702-06e26bc8-2e90-42af-b738-281f53a08197.png">

**Comment by jamestrew** [comment]
Hm... I'm not sure what's happening.
I'm tempted to say it's not a `telescope-file-browser` issue considering that lack of reproducibility but if you're willing to stick around and do something debugging, I can try and help get to the root of the issue.

Can you navigate into `.repro/plugins/telescope-file-browser.nvim/lua/telescope/_extensions/file_browser/finders.lua` and put a `vim.pretty_print(git_file_status)` in line 101 and try steps 5 & 6 above? Then close the file browser and do `:message`.

Should see something like this:
```
{
  ["/tmp/testing/.repro/"] = "??",
  ["/tmp/testing/min.lua"] = "??"
}
```

**Comment by kevinm6** [comment]
I think the same, probably is not a `telescope-file-browser` issue.
Thanks for helping.

I’ve just tried that and I get escape chars:
<img width="751" alt="Screenshot 2023-02-25 at 21 38 34" src="https://user-images.githubusercontent.com/72861758/221378696-ce5ecc6e-5b4b-44ed-a510-9ccda14cc5fa.png">

and I have to figure out where they’re coming.

**Comment by jamestrew** [comment]
Ok yeah there's the issue. 
Never heard of that behavior with `plenary` jobs. I can't find any issues related to it either.
Maybe it's a terminal emulator issue? If you have an alternate terminal you can try with, I'd try that. If that doesn't resolve the issue, I suggest opening an issue upstream with `plenary`.

**Comment by kevinm6** [comment]
Yes, I'm using Kitty as terminal emulator, but I've tried even with macOS default Terminal and I got the same result.
I'll check it better tomorrow.
Thank you for the help!

I'm closing the issue, in case I'll update it with the solution or useful things (like workarounds) for other people.
