### ISSUE TITLE
Crash when opening folder containing `()` characters

### ISSUE THREAD

**Issue by juanpprieto** [nvim-telescope/telescope-file-browser.nvim#244]
### Description

When I try to open a folder containing `(` or `)` I get the following error:

```
[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:484: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:450>
```

### Neovim version

```markdown
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.2.1

### Steps to reproduce

1. Try to open a folder which contains `()` e.g `($lang)`. This is a new pattern supported by [Remix optional segments](https://remix.run/docs/en/v1/file-conventions/route-files-v2#optional-segments) file based routing

### Expected behavior

Expect to be able to navigate to the folder

### Actual behavior

Error
```
[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:484: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:450>
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by juanpprieto** [comment]
Thanks for the prompt response and all the work with this amazing plugin @jamestrew 

> Eg.
> `(foo)/` -> ok
> `$foo/` -> also ok
> `($foo)/` -> not ok

Confirm this is the case for me too 🙏🏼

**Comment by jamestrew** [comment]
Several things I should look into:

- [ ] `async_oneshot_finder` -> `cwd` is being `expand`ed prior to passing `cwd` to uv and the expansion is butchering the path
- [x] regular "grouped" `Job` is fine
- [ ] git status `Job` also fails passing in `cwd`
- [x] `plenary.scandir` is ok 
- [ ] "File Previewer" also fails for both directory and file preview

**Comment by jamestrew** [comment]
@juanpprieto I've determined the cause of this bug (besides the File Previewer). I'll work with the maintainers upstream to figure out a fix but in the meantime, you should be able to do `:Telescope file_browser use_fd=false git_status=false` (or put those in your settings) to get most of the functionality back.

**Comment by juanpprieto** [comment]
Amazing! Thanks @jamestrew `use_fd=false git_status=false` did the trick for the folder access (which was the most pressing issue). File preview is empty, but that less important 🥇

**Comment by fdschmidt93** [comment]
The problem most likely is that the path would have to be escaped for `fd`

> [telescope]     args = { "--base-directory=/tmp/testing/($lang)", "--absolute-path", "--path-separator=/", "--maxdepth", 1 },

like so

`fd --base-directory="/tmp/testing/(\$lang)"` which seems to work in my case appropriately. This seems sensible, because `fd` by default uses a regex syntax.

We should be able to fix this I believe by passing `-F` or `--fixed-strings` which is also more appropriate since we don't want regex.

**Comment by jamestrew** [comment]
I tried the above mentioned fix of adding `--fixed-strings` but in my testing, it doesn't resolve the issue.

I believe for both the `git_status` plenary job and `async_oneshot_finder` use cases, the issue comes down to the passed `cwd` being expanded via `vim.fn.expand`. Altering both of these to just use the provide `cwd` resolves the issue (besides the File Previewer).


https://github.com/nvim-lua/plenary.nvim/blob/253d34830709d690f013daf2853a9d21ad7accab/lua/plenary/job.lua#L68

https://github.com/nvim-telescope/telescope.nvim/blob/a3f17d3baf70df58b9d3544ea30abe52a7a832c2/lua/telescope/_.lua#L24

**Comment by juanpprieto** [comment]
Hi @jamestrew, just ran a `PackerSync` and it seems this issue has regressed. My guess is that it's telescope related but just wanted to let you know.

Now instead of showing an error message, file browser just freezes and I see a telescope messages saying something along the lines of "Nothing selected" when I try to open the ($lang) folder.

One more thing I noticed last week (before this latest changes) is that the following pattern was also breaking:

`/app/routes/($lang)/__public/xyz`

Thanks!

**Comment by juanpprieto** [comment]
Amazing thanks @jamestrew - It's been great following this going upstream 🙏🏼
