### ISSUE TITLE
<CR> doesn't work in insert mode

### ISSUE THREAD

**Issue by aoi-taniguchi** [nvim-telescope/telescope-file-browser.nvim#248]
### Description

As in the title, `<CR>` doesn't work in insert mode.
Explicitly mapping `<CR>` to `require('telescope.actions').actions.select_default` is required.

### Neovim version

```markdown
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 20.04

### Steps to reproduce

1. open file browser
2. hit enter on any file/directory in insert mode

### Expected behavior

any file/directory can be opened in insert mode like in normal mode

### Actual behavior

the cursor goes to its parent directory (i.e., `../`)

### Minimal config

```Lua
I haven't broken down the conditions for reproduction yet.
```

**Comment by aoi-taniguchi** [comment]
If no one else encounters this problem, I'll close this issue.
It might be just my personal environment dependent issue.

**Comment by jamestrew** [comment]
Without any configured bindings, go into `:Telescope file_browser` and in insert mode press `<c-/>`. This will bring up telescope's which-key feature.
You should see `i -> <CR> -> select_default` in the list of key mappings.

You shouldn't have to explicitly map `<CR>` to `select_default` as it's already done so by default.
Also not sure if it's a typo but this isn't correct either. 
> require('telescope.actions').actions.select_default

It would be `require('telescope.actions').select_default` or as a string just `"select_default"`.

**Comment by jamestrew** [comment]
I tried your telescope configuration and the key mappings in insert mode work for me. This must be a configuration issue outside of telescope.

Try `:Telescope file_browser` and go to normal mode and do `:imap <CR>`. Should see something like `i <CR> *@<Cmd>lua require('telescope.mappings').execute_keymap(...)<CR>`

**Comment by aoi-taniguchi** [comment]
I got `i <CR> *@<Cmd>lua require('telescope.mappings').execute_keymap(19, 8)<CR>`.
I'll take a look into what the key id means.
Thank you very much. Much appreciated.

**Comment by jamestrew** [comment]
That looks correct.
Is `file_browser` the only picker where you have this issue?

**Comment by aoi-taniguchi** [comment]
Yes. I have this issue only for `file_browser`.

**Comment by jamestrew** [comment]
I'm pretty confused haha

Can you try this:
1. `mkdir -p /tmp/testing`
2. `cd /tmp/testing`
3. `nvim min.lua` and paste config below
4. re-open nvim with `nvim -nu min.lua`
5. `:Telescope file_browser` and test key bindings

<details>
<summary>min.lua</summary>

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{
		"nvim-telescope/telescope-file-browser.nvim",
		dependencies = {
			"nvim-telescope/telescope.nvim",
			"nvim-lua/plenary.nvim",
		},
		config = function()
      require("telescope").setup()
			require("telescope").load_extension("file_browser")
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
```

</details>

**Comment by aoi-taniguchi** [comment]
Thank you for your cooperation.
It worked fine without explicitly mapping `<CR>` to `select_default`.

Well... , it must be a problem within my nvim environment. I'll keep checking.
Thank you so much for your help.
