### ISSUE TITLE
Fold settings problem

### ISSUE THREAD

**Issue by caasi-dev** [nvim-telescope/telescope-file-browser.nvim#249]
**Is your feature request related to a problem? Please describe.**
Setting to ignore global `foldlevel` and `foldmethod` settings.

**Describe the solution you'd like**
I have the following settings applied:
```
foldlevel = 0
foldmethod = "indent"
```

I load this extension in the following way:
```
vim.keymap.set("n", "sf", function()
	telescope.extensions.file_browser.file_browser({
		path = "%:p:h",
		cwd = telescope_buffer_dir(),
		respect_gitignore = true,
		hidden = true,
		grouped = true,
		previewer = false,
		initial_mode = "normal",
		layout_config = { height = 40 },
	})
end)
```

The fold level settings cause this when opening file browser:
![image](https://user-images.githubusercontent.com/60949037/225549459-69018301-96ab-467f-aee6-ba2e3aa1d5ed.png)

Is there any way fold settings could be ignored in this extension?

**Comment by fdschmidt93** [comment]
Please provide a `minimal_init.lua`.

The below `minimal_init.lua` (load with nvim -u `minimal_init.lua`) does not reproduce the issue.

Please consider going forward that the issue template is there for a reason such that maintainers do not have to ask for background questions. Please fill out the template and provide required info.

**Comment by caasi-dev** [comment]
Thanks for your quick answer. I have used the feature request template, and the last 2 questions were something that I felt I answered in above description. Feature request template did not ask for `minimal_init.lua`, but yes, I could've thought of adding it, sorry.

Seems there is some other setting that interferes. I will report back when find a solution.

**Comment by fdschmidt93** [comment]
Here's a simple workaround that you can add to your config:

```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "TelescopeResults",
  command = "setlocal foldmethod=manual",
})
```

I believe we'd have to solve this over at `telescope.nvim` otherwise when the options are set for a window to be created.

**Comment by caasi-dev** [comment]
This works for me on my full config, thanks for rapid workaround!
This solution is satisfactory to me personally, thanks a lot!
