### ISSUE TITLE
Mapping toggle selection breaks this extension

### ISSUE THREAD

**Issue by minizilla** [nvim-telescope/telescope-file-browser.nvim#261]
### Description

I'm mapping telescope toggle selection and it break when using it in telescope-file-browser extensions.

Not sure if this is a bug in the telescope itself or in this extensions, but the mappings works for builtins pickers. I'll create issue in the telescope if this is telescope bug.

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

NixOS 23.05

### Steps to reproduce

```lua
local telescope = require('telescope')
local actions = require('telescope.actions')

telescope.setup {
  defaults = {
    mappings = {
      i = {
        ['<S-Down>'] = actions.add_selection + actions.move_selection_next + actions.add_selection,
        ['<S-Up>'] = actions.add_selection + actions.move_selection_previous + actions.add_selection,        
      },
    },
  },
}

telescope.load_extension('file_browser')
```

1. Use above configurations
2. Open **telescope-file-browser** `:Telescope file_browser`
3. Use the custom mapping `Shift + Down` or `Shift + Up`
4. Watch it break

### Expected behavior

Custom toggle selections should work with the extensions just like it works with builtins pickers.

### Actual behavior

It break with the following error.

```shell
E5108: Error executing lua ...Packages/start/telescope.nvim/lua/telescope/mappings.lua:350: attempt to call local 'key_func' (a table value)
stack traceback:
        ...Packages/start/telescope.nvim/lua/telescope/mappings.lua:350: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

### Minimal config

```Lua
local telescope = require('telescope')
local actions = require('telescope.actions')

telescope.setup {
  defaults = {
    mappings = {
      i = {
        ['<S-Down>'] = actions.add_selection + actions.move_selection_next + actions.add_selection,
        ['<S-Up>'] = actions.add_selection + actions.move_selection_previous + actions.add_selection,        
      },
    },
  },
}

telescope.load_extension('file_browser')
```

**Comment by fdschmidt93** [comment]
My hunch is this is a problem with `actions` metatable and how it plays with telescope extensions.

A workaround that should work for the time being would be

```lua
      i = {
        ['<S-Down>'] = function(prompt_bufnr)
          actions.add_selection(prompt_bufnr)
          actions.move_selection_next(prompt_bufnr)
          actions.add_selection(prompt_bufnr)
        end,
     
      },
```

Though I'm not sure I understand the use case of your custom mapping at first glance. There's actions to toggle eg all entries for selection.

**Comment by minizilla** [comment]
Nvm, just update the version and it solved.
