### ISSUE TITLE
See just filenames when peeking into folder

### ISSUE THREAD

**Issue by mareksubocz** [nvim-telescope/telescope-file-browser.nvim#267]
**Is your feature request related to a problem? Please describe.**
My screen real estate is limited and I often can't see what's inside a folder i'm currently focused on because of additional info such as permissions, ownership, date created etc.

**Describe the solution you'd like**
Is it possible to add an option to hide that info?

**Describe alternatives you've considered**
The filename could also be moved to the left to mimick what it looks like in the main pane.

**Additional context**
<img width="958" alt="image" src="https://user-images.githubusercontent.com/36044757/235325880-eb5a11f0-f029-4a67-a258-4d5519631b97.png">

**Comment by jamestrew** [comment]
I've had similar requests before. I agree it would be a useful feature. I will prioritize this but this may take some time.
In the mean time, you can play around with the layout config. Maybe doing something like `:Telescope file_browser theme=dropdown` can be an intermediate fix.

**Comment by mareksubocz** [comment]
I'm not too familiar with this codebase, but the output in the right window looks like ```ls -l``` output. If that's true, can you show me where it happens in the code? I could just swap it for ```ls -1``` for a workaround.

**Comment by kynantokoro** [comment]
I was also finding a way to do this.

I may be wrong, but upon quick inspection, it seems to be more of an issue with the default previewer in telescope.nvim that uses the ls_async function from plenary.nvim. This function always uses the long option. 

https://github.com/nvim-telescope/telescope.nvim/blob/713d26b98583b160b50fb827adb751f768238ed3/lua/telescope/previewers/buffer_previewer.lua#L179

https://github.com/nvim-lua/plenary.nvim/blob/9ac3e9541bbabd9d73663d757e4fe48a675bb054/lua/plenary/scandir.lua#L586

**Comment by jamestrew** [comment]
^ that's correct. The file previewer code is nested pretty far upstream even beyond telescope.
I don't want to create a separate file previewer just for telescope-file-browser so I'm looking at adding a new option for all picker using that previewer not use the `-l` option for `ls`.

**Comment by jamestrew** [comment]
Does this look good?
![image](https://user-images.githubusercontent.com/66286082/235371146-1b7ea01a-7b6b-444a-be7b-ccdc8a4cf0bf.png)

**Comment by kynantokoro** [comment]
looks great to me!

**Comment by mareksubocz** [comment]
very much so!

**Comment by jamestrew** [comment]
PR got merged into telescope master.
If you're on the master branch (at the time of this comment) for upstream telescope (not telescope-file-browser), you can now set `preview = { ls_short = true }` in one of the two places as shown below in your config to get the desired behavior. 
```lua
require("telescope").setup({
  defaults = {
    -- ...
    preview = {
      ls_short = true,
    }
  }
  extensions = {
    file_browser = {
      -- ...
      preview = {
        ls_short = true,
      }
    }
  }
})
```

I think I can mark this issue as closed.
