### ISSUE TITLE
"tsallow" file to overwrite the gitignore

### ISSUE THREAD

**Issue by twiclo** [nvim-telescope/telescope-file-browser.nvim#270]
**Is your feature request related to a problem? Please describe.**
I have config files in my repo that shouldn't be committed however I still want to be able to pull them up in telescope.

**Describe the solution you'd like**
A "tsallow" file that explicitly adds filenames contained within to even if they're in the gitignore.

**Describe alternatives you've considered**
Writing my own picker

**Comment by jamestrew** [comment]
To my knowledge there isn't a clean way of accomplishing this with flags for `fd`.

My recommendation will be to use `.fdignore` (or just `.ignore`) to whitelist files of interest https://github.com/sharkdp/fd/issues/503

This way things can be git repository specific and we can take advantage of `fd` better than hacking in our own solution. 

I hope that helps.
