### ISSUE TITLE
File browser gets very laggy with folder/file named {{...}}

### ISSUE THREAD

**Issue by tmwatchanan** [nvim-telescope/telescope-file-browser.nvim#273]
### Description

If the folder structure contains `{{...}}` as a name of file/directory, it would cause a laggy behavior for the file browser.

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.3.1

### Steps to reproduce

1. Have the following folder structure
```
.
├── baz
├── foo
├── something.py
└── {{test}}
    ├── **browse_to_this_level!**
    ├── haha.py
    ├── omg.py
    ├── test.py
    └── {{baz}}
```
2. Open Neovim
3. Open the file browser and browse to the deepest level
4. Notice the lag

### Expected behavior

Although the folders/files have the format of `{{..}}`, I would like it to be as snappy as the usual case.

### Actual behavior

The file browser isn't responsive to the file browsing. It's noticeable without measuring the time.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Hey thanks for reporting.
However I'm not able to replicate. Can you verify what I'm doing is how you're experiencing the lag?

https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/66286082/03753f14-c2eb-44c6-8238-939a878c8dee

**Comment by tmwatchanan** [comment]
The video above doesn't experience any lag at all. Can you please try to reproduce this issue with the minimal config attached?

**Comment by jamestrew** [comment]
Yeah sorry same experience using the minimal config
