### ISSUE TITLE
Initialize in normal mode instead of insert mode

### ISSUE THREAD

**Issue by lrgalego** [nvim-telescope/telescope-file-browser.nvim#274]
Loved the plugin!

The only thing that goes into my flow is that is starts in insert mode. 
Would be great to have a setting to start it in normal mode.

**Comment by jamestrew** [comment]
There's a `initial_mode = "normal"` option you can set that we inherit from upstream telescope.

**Comment by thomascrha** [comment]
Is there a way todo this conditionally though ? I'm aware of setting this setting in the pickers 

i.e.

```
require "telescope".setup {
  pickers = {
    buffers = {
      initial_mode = "normal"
    }
  }
}
```

But that will make it so that all my pickers are in normal mode - What I would like is to be able to set just the file_browser to use normal mode.

**Comment by jamestrew** [comment]
@thomascrha using that snippet, only the `buffers` picker should start in normal mode provided you've set the the `initial_mode` under the `defaults` as "insert".

To have file_browser start in normal mode, you can just apply the `initial_mode = "normal"` under the file_browser settings
```lua
require("telescope").setup {
  extensions = {
    file_browser = {
      initial_mode = "normal",
      -- ...
    },
  },
}```
