### ISSUE TITLE
[Feature] Add `live_grep` action

### ISSUE THREAD

**Issue by pidgeon777** [nvim-telescope/telescope-file-browser.nvim#275]
`Telescope` provides a `live_grep` picker to find text inside files.

This picker supports some arguments such as:

- `cwd_string`: root dir to search from.
- `search_dirs`: a table of directories/files to search.

It would be great to add an action to `telescope-file-browser` so that the the `search_dirs` table is built according to the selected items, and a live grep is started with a dedicated keybinding.

**Comment by jamestrew** [comment]
These sorts of actions which integrate with other pickers from telescope can be so dependent on the individual in terms of how it should function, even though I use them myself regularly, I'm not sure they're a great candidate for including into telescope-file-browser. 

I'll probably start a "Actions" category in this repo's wiki.

In the meantime, I think something like this might fit what you're looking for.
```lua
local fb_utils = require("telescope._extensions.file_browser.utils")
local grep_selections = function(prompt_bufnr)
  local selections = fb_utils.get_selected_files(prompt_bufnr)
  local search_dirs = vim.tbl_map(function(path) return path:absolute() end, selections)
  actions.close(prompt_bufnr)
  require("telescope.builtin").live_grep({ search_dirs = search_dirs })
end
```

**Comment by pidgeon777** [comment]
I did this:

```lua
local fb_utils = require("telescope._extensions.file_browser.utils")
local grep_selections = function(prompt_bufnr)
  local selections = fb_utils.get_selected_files(prompt_bufnr)
  local search_dirs = vim.tbl_map(function(path) return path:absolute() end, selections)
  actions.close(prompt_bufnr)
  require("telescope.builtin").live_grep({ search_dirs = search_dirs })
end

...

mappings = {
  ["i"] = {
    ["<C-z>"] = grep_selections,
  },
},
```

The problem is that nothing happens when activating Ctrl+Z. Tested both when the cursor was on a file/folder and when one or multiple telescope items were selected.
