### ISSUE TITLE
Filenames are not visible

### ISSUE THREAD

**Issue by neerajnigam6** [nvim-telescope/telescope-file-browser.nvim#276]
### Description

Telescope buffer and Telescope-file-browser does not display filenames. 
I can see icons, however there is no filename next to it.

--- see attached screenshots.
https://imgur.com/a/RSpPwn2

--- file browser shows icons but no filename along with it.

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

MacOS 13.3

### Steps to reproduce

deafult configuration for Telescope.

### Expected behavior

Filename along with icons in telescope-file-browser, and telescope buffers.

### Actual behavior

Icons along with filename/buffer title displayed while using default config for telescope.

### Minimal config

```Lua
require("telescope").setup {
  picker = {
    theme = "ivy"
  },

  extensions = {
    file_browser = {
        theme = "ivy",
        -- disables netrw and use telescope-file-browser in its place
        hijack_netrw = true,
--        cwd_to_path = true,
--        grouped = true,
--        files = true,
       auto_depth = 2,
        git_status = true,
        mappings = {
          ["i"] = {
            -- your custom insert mode mappings
          },
          ["n"] = {
            -- your custom normal mode mappings
          },
        },
      },
  },
}
require("telescope").load_extension "file_browser"


---- installed plugins

require('packer').startup(function(use)
--   [[ Plugins Go Here ]]
   
    use 'tjdevries/colorbuddy.nvim'
    use 'bkegley/gloombuddy'
    use 'neovim/nvim-lspconfig'
    use 'anott03/nvim-lspinstall'

    -- nvim cmp related plugins
    use 'hrsh7th/cmp-nvim-lsp'
    use 'hrsh7th/cmp-buffer'
    use 'hrsh7th/cmp-path'
    use 'hrsh7th/cmp-cmdline'
    use 'hrsh7th/nvim-cmp'

    -- snip config
    use 'hrsh7th/cmp-vsnip'
    use 'hrsh7th/vim-vsnip'
    use 'hrsh7th/vim-vsnip-integ'
    -- sneaking some formatting in here too
    use {'prettier/vim-prettier', run = 'yarn install' }
    use 'nvim-treesitter/nvim-treesitter'
    use 'nvim-lua/plenary.nvim'
    use {
      'nvim-telescope/telescope.nvim', tag = '0.1.1',
    -- or                            , branch = '0.1.x',
      requires = { {'nvim-lua/plenary.nvim'} }
    }
      use 'BurntSushi/ripgrep'
    use 'natecraddock/nvim-find'
    use 'nvim-tree/nvim-web-devicons'
    use {
        "nvim-telescope/telescope-file-browser.nvim",
        requires = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" }
    }
    use 'sheerun/vim-polyglot'
    use 'nvim-lua/popup.nvim'
    use 'jremmen/vim-ripgrep'
    -- [[ Theme ]]
end)
```

**Comment by jamestrew** [comment]
Are you on telescope master? I think there was a temporary bug. If you are, try updating telescope.

**Comment by neerajnigam6** [comment]
I am on telescope 0.1.1 tagged version, not sure this is the latest version.

**Comment by jamestrew** [comment]
Strange, your issue seems identical to https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/272 
https://github.com/nvim-telescope/telescope.nvim/issues/2528

I tried to replicate this using your telescope config and using the same tagged version but I was unable to. When did you start experiencing this issue. the 0.1.1 release hasn't been changed since mid-January.

**Comment by neerajnigam6** [comment]
Hey,  Yes my issue is identical to this, I am new to nvim. Thanks for pointing to the original issue, it looks like this issue is with telescope and not the file browser extension. Closing this issue here, will followup on Telescope repo for the bug.
