### ISSUE TITLE
Select file when opened with path to file

### ISSUE THREAD

**Issue by uloco** [nvim-telescope/telescope-file-browser.nvim#277]
**Is your feature request related to a problem? Please describe.**
I'd like the current file to be highlighted when I open it with the path to the file.

Like so 

```lua
    telescope.extensions.file_browser.file_browser({
      path = "%:p"
    })
```

**Describe the solution you'd like**
Select the current file if path is a file. Currently only directories are allowed with `%:p:h`

**Comment by jamestrew** [comment]
This can be achieved with this command `:Telescope file_browser path=%:p:h select_buffer=true`

`select_buffer = true` is the option for selecting the buffer file in the results window.

**Comment by uloco** [comment]
oh i was not aware of that, thank you!
