### ISSUE TITLE
Query-triggered actions

### ISSUE THREAD

**Issue by musjj** [nvim-telescope/telescope-file-browser.nvim#288]
**Is your feature request related to a problem? Please describe.**
There was this neat feature from Ivy on Emacs that I sorely miss. What it does is that it triggers certain actions automatically based on the current contents of you search query. Is this possible with Telescope's API?

**Describe the solution you'd like**
Here are a few examples that I remember from the top of my head.
Search queries that begins with:
- A `.` will automatically make hidden files visible in the current directory 
- A `~/` will change the current directory to the root of your home directory
- A `/` followed by a letter will bring you to the system root
- (On Windows) A letter followed by `:/` (`c:/`, `d:/`, etc.) will change the current system drive

**Describe alternatives you've considered**
A traditional shortcut can fulfill this need, but I think this method is a lot more elegant and seamless.

**Comment by fdschmidt93** [comment]
Yes, it's actually quite straightforward. Let yourself be inspired by this issue

https://github.com/nvim-telescope/telescope.nvim/issues/1042

and 

telescope-file-browser actions.

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/actions.lua

The telescope repo also has more input on customization

https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md
