### ISSUE TITLE
  A Reverse range in character class error when previewing files folder with specific name

### ISSUE THREAD

**Issue by huypl53** [nvim-telescope/telescope-file-browser.nvim#289]
### Description

file path contains double bracket like `app/sign-in/[[...sign-in]]/SigninForm.tsx` could not open

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 22.04 LTS     

### Steps to reproduce

when I suppose to open file with double bracket like `app/sign-in/[[...sign-in]]/SigninForm.tsx`,  and file is not loaded 

### Actual behavior

I get warning only
`[telescope] [WARN  14:56:07] /home/huy/.local/share/nvim/site/pack/packer/start/telescope.nvim/lua/telescope/pickers.lua:493: Finder failed with msg:  Vim:E944: Reverse range in character class`

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Hi, I'm assuming this issue is related to `telescope-file-browser` (`:Telescope file_browser`). I can reproduce it using it but not `find_files`.

**Comment by Conni2461** [comment]
I think that was only a partial fix in plenary

**Comment by jamestrew** [comment]
Had to revert https://github.com/nvim-telescope/telescope.nvim/pull/2599

**Comment by Amar-Gill** [comment]
I also get this error when trying to open the telescope file browser when there is single bracket in the directory name (like many js frameworks do now).

The file path in my scenario is: `/nuxt-todo/pages/users/[user-id]/`.

The error message:

```bash
Error executing vim.schedule lua callback: Vim:E944: Reverse range in character class
stack traceback:
        [C]: in function 'expand'
        ...er.nvim/lua/telescope/_extensions/file_browser/utils.lua:216: in function 'to_absolute_path'
        ...r.nvim/lua/telescope/_extensions/file_browser/picker.lua:89: in function 'fb_picker'
        ...-browser.nvim/lua/telescope/_extensions/file_browser.lua:90: in function 'file_browser'
        ...r.nvim/lua/telescope/_extensions/file_browser/config.lua:110: in function <...r.nvim/lua/telescope/_extensions/file_browser/config.lua:89>
```

**Comment by gonstoll** [comment]
Having the same result here. Oddly, this happens when trying to access `/app/sign-in/[[...sign-in]]`. However, this does not happen when navigating to `/app/sign-up/[[...sign-up]]` 🤔

**Comment by jamestrew** [comment]
> Having the same result here. Oddly, this happens when trying to access /app/sign-in/[[...sign-in]]. However, this does not happen when navigating to /app/sign-up/[[...sign-up]] 🤔

That's because the contents in between the `[]` is being interpreted as a regex range by vim's `expand` function. `n-i` is not a valid range of characters (not in alphabetical order) while `n-u` is.

But that's besides the point. Really we need to find a clever way to not `expand` paths when it's a valid path. This has been tricky since upstream telescope liberally uses `expand` and it's like a whac-a-mole crossed with a minefield.
