### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by fdschmidt93** [nvim-telescope/telescope-file-browser.nvim#29]
### Description

Finder performance currently is abysmally slow compared to what it should be. My hunch is that the metatable gymnastics of [finders](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/finders.lua) significantly slow down the picker.

This can be observed with folder browsing in very large repositories. Compared to a plain custom plenary.scandir picker ala

```lua
local scan = require("plenary.scandir")
local finders = require("telescope.finders")
local pickers = require("telescope.pickers")
local conf = require("telescope.config").values

local make_entry = function(entry)
	return { ordinal = entry, display = entry, value = entry }
end

local pick_folders = function(opts)
	opts = opts or {}

	local cwd = vim.loop.cwd()
	opts.depth = vim.F.if_nil(opts.depth, 1)
	opts.cwd = opts.cwd and vim.fn.expand(opts.cwd) or cwd
	opts.path = opts.path and vim.fn.expand(opts.path) or cwd
	opts.files = vim.F.if_nil(opts.files, true)
	pickers.new(opts, {
		prompt_title = "Folder Browser",
		finder = finders.new_table({
			results = scan.scan_dir(vim.loop.cwd(), { only_dirs = false }),
			entry_maker = make_entry,
		}),
		previewer = conf.file_previewer(opts),
		sorter = conf.file_sorter(opts),
	}):find()
end
```

The file browser extension is extremely slow. Once the finder of finders is bypassed, the extension is just as fast. That'll require some more investigation.

### Neovim version

```markdown
NVIM v0.7.0-dev+717-gf37c5f180
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/fdschmidt/.cache/paru/clone/neovim-git/src/build/config -I/home/fdschmidt/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/fdschmidt/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/fdschmidt/.cache/paru/clone/neovim-git/src/build/include
Compiled by fdschmidt

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

### Operating system and version

Arch Linux

### Steps to reproduce

1. Go to large repository with thousands of folders
2. Attempt to folder browse

### Expected behavior

Browsing should be very fast as plenary.scandir is extremely fast.

### Actual behavior

Very slow browsing.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
(Note beforehand: it's much much better when using `fd` to the degree that the problem is almost entirely alleviated, only significant then if `depth=false`)

The problem here is likely two-fold:

1. entry maker
2. meta table

The entry maker significantly slows down the finder -- you can try this with file-browser entry maker

```lua
local scan = require("plenary.scandir")
local finders = require("telescope.finders")
local pickers = require("telescope.pickers")
local conf = require("telescope.config").values
local make_entry =  require "telescope._extensions.file_browser.make_entry"

local pick_folders = function(opts)
	opts = opts or {}

	local cwd = vim.loop.cwd()
	opts.depth = vim.F.if_nil(opts.depth, 1)
	opts.cwd = opts.cwd and vim.fn.expand(opts.cwd) or cwd
	opts.path = opts.path and vim.fn.expand(opts.path) or cwd
	opts.files = vim.F.if_nil(opts.files, true)
	opts.entry_cache = {}
	pickers.new(opts, {
		prompt_title = "Folder Browser",
		finder = finders.new_table({
			results = scan.scan_dir(vim.loop.cwd(), { only_dirs = true }),
			entry_maker = make_entry(opts),
		}),
		previewer = conf.file_previewer(opts),
		sorter = conf.file_sorter(opts),
	}):find()
end
```

But this is only partially the cause, as even then it's very noticeably faster to the current state of things.

meta-table finder is just a hunch, but atm don't see what else is causing it, cf

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/finders.lua#L81-L116

**Comment by fdschmidt93** [comment]
@Conni2461 

just FYI since you might find this interesting, I found the culprit. `opts.respect_gitignore` i.e.  

```lua
  local log = require "telescope.log"
  local start_time = vim.loop.hrtime()
  local data = scan.scan_dir(vim.loop.cwd(), {
    hidden = true,
    only_dirs = true,
    -- oof
    respect_gitignore = true,
  })
  local end_time = vim.loop.hrtime()
  log.warn(string.format("folder finding took %s ms", (end_time - start_time) / 1e6))
```

increases folder finding across c.5K folders by 10x (~70->~700ms).

**Comment by Conni2461** [comment]
Respecting gitignore is insanely hard. All i supported was if you ignore dir `abc` i dont take path `abc` or if you ignore file `test.lua` i wont add test.lua to it.

But someone rewrote it so more stuff is incorporated and maybe that made it even worse.

Because technically you could ignore `abc` but include `abc/file` so you still need to walk that path. And other stuff like `gitignore`s in each level. I wouldnt use it :grimacing: 

I dont think it makes sense for a file browser anyways. Like you want a raw view of whats in your directory like `ls` with or without `-a`.

And with a potential telescope-rs backend we could just use a ripgrep crate to do it programmatically async and remove the additional spawn/parsing overhead: https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore
