### ISSUE TITLE
Create a mapping to change to a custom directory

### ISSUE THREAD

**Issue by lucasmarinb** [nvim-telescope/telescope-file-browser.nvim#290]
The mapping `<C-e>`  changes to the home directory and `<C-w>` changes to the currently selected. Is there any way to make a custom keymapping to change to a custom directory?

I've tried creating a custom mapping with the `nvim_set_current_dir` api but i couldn't figure it out.

**Comment by jamestrew** [comment]
If you want an action to go to a known directory, you can write a small custom action and bind this to your desired mapping

```lua
local goto_my_dir = function(prompt_bufnr)
  local current_picker = action_state.get_current_picker(prompt_bufnr)
  local finder = current_picker.finder
  finder.path = "/path/to/my/dir" -- change this

  fb_utils.redraw_border_title(current_picker)
  current_picker:refresh(
    finder,
    { new_prefix = fb_utils.relative_path_prefix(finder), reset_prompt = true, multi = current_picker._multi }
  )
end
```

**Comment by lucasmarinb** [comment]
Thank you, that was exactly what I wanted!
