### ISSUE TITLE
Any way to temporarily ignore the ignores of ripgrep?

### ISSUE THREAD

**Issue by benfrain** [nvim-telescope/telescope-file-browser.nvim#291]
Very occasionally I would like to search through files/folders that ripgrep ordinarily ignores (eg node_modules) with file-browser

**Describe the solution you'd like**
A means to temporarily provide access to those folders and files. Kind of like how you can show hidden files

**Comment by jamestrew** [comment]
This is something I occasionally do as well so I'm open to adding this feature as a toggle-able action.

**Comment by jamestrew** [comment]
Do you think toggling just the `respect_gitignore` option we already have is enough? There is a `--no-ignore` option for fd that would go beyond ignoring gitignore and ignore a bunch of other things:

```
       -I, --no-ignore
              Show search results from files and directories that would otherwise be ignored by

              • .gitignore

              • .git/info/exclude

              • The global gitignore configuration (by default $HOME/.config/git/ignore)

              • .ignore

              • .fdignore

              • The global fd ignore file (usually $HOME/.config/fd/ignore )

              The flag can be overridden with ’‐‐ignore’.
```

If we wanted to go with the latter option, it might also make sense to expose some new `respect_ignore` option as well but I'm trying to avoid piling on more and more options.

I think just gitignore would cover 99% of use cases.

**Comment by benfrain** [comment]
Just toggling the respect_gitignore seems the most sensible place to start. Especially if that’s relatively simple to implement.

**Comment by rodhash** [comment]
Is the default keybinding <Ctrl-h> already showing node_modules?  It seems to me it's only toggling hidden files .. tried temporarily removing my .gitignore but I don't see this particular directory  yet .. do I need to change or enable something on my default mapping for <c-h>?

**Comment by rodhash** [comment]
Oh nevermind, got it working .. thanks for this new action very nice
