### ISSUE TITLE
Last commit seems to have broken the folder-browser

### ISSUE THREAD

**Issue by svanharmelen** [nvim-telescope/telescope-file-browser.nvim#294]
### Description

When using `:Telescope file_browser files=false` the picker window remains empty so I cannot select any directories:

<img width="1225" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/4171547/d1653dac-473b-4e07-850b-dd5ca5626581">

Reverting the last commit fixes the problem, so it seems to be an issue with 6c234e863444c246611ad7458185c771ad8cd6e6

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.4.1

### Steps to reproduce

Starting Telescope with: `:Telescope file_browser files=false`

### Expected behavior

Directories should be listed in the picker windows so you are able to select them.

### Actual behavior

No directories are listed and so none can be selected.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Oops. Sorry about that. Should be fixed in the latest commit.
Thanks for reporting :+1:

**Comment by svanharmelen** [comment]
Thanks!

**Comment by skirge** [comment]
Ubuntu 20.04 has fd version 0.7.4 which was not working (file browser empty) and I had to uninstall it. Wasted half a day because of that.

**Comment by jamestrew** [comment]
@skirge sorry to heard that. It turns out that on ubunto, fd is actually called fdfind due to name clashing. The readme for fd actually suggest you "rename" the binary to `fd` https://github.com/sharkdp/fd#on-ubuntu

This plugin will work without fd, but checking whether you have the correct fd is not something we currently do.
I'll try to make some changes on our side to better accommodate this discrepancy in the binary name as well.

**Comment by skirge** [comment]
I did that (fdfind linked to /usr/local/bin/fd) but it seems it doesn't like option `--base-directory`   used here: https://github.com/nvim-telescope/telescope-file-browser.nvim/commit/4054a5d0ab85475bf75df00cf10754d2e54b5532#diff-5516c6e306989f4f6688942642c09b426e9da67fa2022dff6b3ff97973400707

```
fdfind --base-directory=~/tmp/ --type file --absolute-path --path-separator=/                                                                                                                                            
error: Found argument '--base-directory' which wasn't expected, or isn't valid in this context
fdfind --version                                                                                                                                                                                                           
fd 7.4.0
```

**Comment by jamestrew** [comment]
@skirge should work for you now with https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/299
I've also added better error handling in a separate commit to help catch these kinds of issues in the future.
