### ISSUE TITLE
Open in folder_browser instead of file_browser

### ISSUE THREAD

**Issue by seagoj** [nvim-telescope/telescope-file-browser.nvim#296]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to use telescope to create files/directories from a keymap. The folder browser mode fulfills this, but I haven't found a way to start in that mode from a keymap.

**Describe the solution you'd like**
The ability to launch the folder_browser with something like `:Telescope folder_browser`

**Describe alternatives you've considered**
I'm open to alternatives, but not sure what they would be offhand

Thanks for your attention

**Comment by jamestrew** [comment]
You can you `:Telescope file_browser files=false` :+1: 

> I am looking for a way to use telescope to create files/directories from a keymap.

For this though, you can still be in the file_browser "mode". Unless I'm confused with what you're trying to do.

**Comment by seagoj** [comment]
That works for me. Thanks!
