### ISSUE TITLE
Question: Is it possible to create a shortcut to open a file in a specific window?

### ISSUE THREAD

**Issue by svanharmelen** [nvim-telescope/telescope-file-browser.nvim#306]
As the title mentions, is there any way to open a file in a specific window?

I usually have 3 or 4 windows open next to each other and when I need a file I just hit my shortcut to open the file-browser and select the file. But often I don't want to load the file I'm searching for in the window I'm currently working in, but in the one left or right from it.

I know you can open a file in a new window, but it would be awesome if there is a way to create a shortcut that (for example) closes Telescope after selecting a file, but then asks a window number to open the file in. Or alternatively a shortcut for a given (fixed) window number would also be helpful (would mean I need 3 or 4 a few fixed shortcuts, but would still be helpful).

Very curious to learn if there are building block or helper functions available to make that possible. Thanks!!

**Comment by svanharmelen** [comment]
Yes, I indeed meant `window` instead of `buffer`! Sorry for the confusion (for readability I updated the initial text above 😊)

I know about opening a file in a new split (with `<C-v>` for example), but I would prefer to reuse an existing window instead of opening another one. I know NvimTree supports such a feature (as I used that before), but no idea how hard it would be to mimic something like that with the file-browser.

**Comment by jamestrew** [comment]
Are you referencing the `o` key binding in nvim-tree? 
I'm not sure if something like that is necessary for telescope-file-browser since we use a floating window and open the buffer in the last used window. I think you can just switch to the window where you want your file/buffer to be opened, open file-browser, open the file.

**Comment by svanharmelen** [comment]
Thanks for your reaction. And yes, that is exactly what I'm referring to.

I know I can move to the window before starting the file-browser, but as I often want to open the new file in a new window one or two windows next to where I'm currently working this is kind of annoying.

Especially considering I'm working in a very large project where I have to switch back and forward between files almost constantly.

Sometimes just to double check/compare what choices were made in that oart of the code, bit often to make small updates as well.

So my workflow would really benefit from being able to open the file-browser from wherever I am and determine the window to open the selected file while opening it.

Of course a complete/working solution would be great, but I understand it probably doesn't exist at the moment. So any pointer or helper functions that could maybe be used to create a custom binding would make a great starting point for me to try and create something for this.

Thanks!

**Comment by gegoune** [comment]
There are
- https://github.com/s1n7ax/nvim-window-picker
- https://github.com/ten3roberts/window-picker.nvim

You can probably add custom action bind to some key to invoke one of those plugins.

**Comment by svanharmelen** [comment]
I had some time today and tried to create a custom mapping using the suggested window picker. It seems to workout exactly how I would like, but I fail to chain the actions in order for the file to be opened correctly

This is the action I defined:
```lua
local transform_mod = require('telescope.actions.mt').transform_mod

local window_picker = transform_mod({
  select = function(prompt_bufnr)
    local winid = require('window-picker').pick_window()
    vim.api.nvim_set_current_win(winid)
  end,
})
```

And these are my mappings:
```lua
    mappings = {
      i = {
        ['<C-j>'] = actions.move_selection_next,
        ['<C-k>'] = actions.move_selection_previous,
        ['<C-o>'] = window_picker.select + actions.select_default,
        ['<C-q>'] = actions.smart_send_to_qflist + actions.open_qflist,
        ['<ESC>'] = actions.close,
      },
    },
```

So I mapped `<C-o>` and when I press that while on a file, it gives me the picker and changes to the window I've selected. But after that `actions.select_default` fails to open the file with this error:

```lua
E5108: Error executing lua: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1445: attempt to index local 'picker' (a nil value)
stack traceback:
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1445: in function 'on_close_prompt'
        ...acker/start/telescope.nvim/lua/telescope/actions/set.lua:172: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:257: in function <...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:256>
```

Is there anything wrong with my action? Or is this somehow caused by the window being changed without telescope being aware of that?

**Comment by svanharmelen** [comment]
Ah... Never mind, I solved it but updating my action to this:

```lua
local window_picker  = transform_mod({
  select = function(prompt_bufnr)
    local action_state = require("telescope.actions.state")
    local picker = action_state.get_current_picker(prompt_bufnr)
    picker.original_win_id = require('window-picker').pick_window()
  end,
})
```

Quite simple and elegant if you ask me, so happy with the result 👍🏻 

Thanks @gegoune and @jamestrew for you input and suggestions!

**Comment by protivinsky** [comment]
Thanks for the snippet, works still well!

As I use `hint = 'floating-big-letter'` with windows-picker, I also had to add to its setup config `buftype = { "prompt", "nofile" }` to filter_rules, to avoid letters for selection even on telescope windows.
