### ISSUE TITLE
Git status not displayed when changing directory

### ISSUE THREAD

**Issue by hschne** [nvim-telescope/telescope-file-browser.nvim#309]
### Description

Similar to #243. Showing the git status of files breaks when the user changes the working directory away from the git root. 

I assume that the parsing of the git status output does not correctly account for changes in directory. 

```lua
-- lua/telescope/_extensions/file_browser/git.lua
M.parse_status_output = function(output, cwd)
  local parsed = {}
  for _, value in ipairs(output) do
    local mod, file = value:match "^(..) (.+)$"
    if mod:find "[RC]" then
      file = file:match "^.* -> (.+)$"
    end
    parsed[Path:new({ cwd, file }):absolute()] = mod
  end
  return parsed
end
``` 

### Neovim version

```markdown
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958
```

### Operating system and version

Arch Linux x86_64

### Steps to reproduce

1. Create a new folder with a subfolder `sub` and some basic files, initialize git.
    ```
    mkdir folder && cd folder
    mkdir sub && touch sub/sub.txt
    git init
    git commit -a -m "Whatever"
    ```
2. Make any changes in the sub folder
   ```
   echo "Content" > sub/sub.txt
   touch sub/new.txt
   ```
3. Open vim and CD away from the git root from within vim
   ```
   nvim .
   :cd sub
   ```
4. View the files using `:Telescope file_browser git_status=true`

### Expected behavior

The git status of the files should be shown.

### Actual behavior

After changing the current directory with `cd` away from the git root, the git status of the files is no longer shown. 

Before CD            |  After CD
:-------------------------:|:-------------------------:
![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/5294464/649d2bc4-57d8-4e92-9fff-9079e34923b2)  |  ![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/5294464/24059c17-0a38-4558-9a99-ad8f0aac6584)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Thanks for the detailed report - I'm able to replicate this.
I think this is due to how `git status --porcelain -- .` (which we parse to get the git statuses) always give paths relative to the toplevel directory of the git repo.

I'll just have to take that into account.

**Comment by hschne** [comment]
Wow, you made quick work of that! Thanks a ton! 💯
