### ISSUE TITLE
sort = "recent"

### ISSUE THREAD

**Issue by utfeight** [nvim-telescope/telescope-file-browser.nvim#311]
## Feature

Caching the recent files visited, then using this data to sort them while navigating

I like this feature because it speeds up the file navigation stuff a lot.
I'm familiar to this from doomemacs dired-mode

**Comment by CleoMenezesJr** [comment]
Sort by file type would be nice too. I would like to be able to see the directories first and then the files, for example

**Comment by jamestrew** [comment]
> Sort by file type would be nice too. I would like to be able to see the directories first and then the files, for example

I think what you're asking for is the `grouped` option.

**Comment by jamestrew** [comment]
I think the original request would be far more involved. I'm personally not that interested in implementing (and more importantly, maintaining) something like that at the moment.

**Comment by untimated** [comment]
> > Sort by file type would be nice too. I would like to be able to see the directories first and then the files, for example
> 
> I think what you're asking for is the `grouped` option.

YES THIS IS IT

![Image](https://github.com/user-attachments/assets/c455394e-946a-48cb-a3da-7d4b06811b86)
