### ISSUE TITLE
start: Executable not found

### ISSUE THREAD

**Issue by peter-lyr** [nvim-telescope/telescope-file-browser.nvim#314]
### Description

fb_actions.open failed in windows 10

![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/55801796/e8f5d88d-2432-47d8-b03a-5acc0089a910)

I want to open some file with system method, here is where the error caused.

```lua
fb_actions.open = function(prompt_bufnr)
  local quiet = action_state.get_current_picker(prompt_bufnr).finder.quiet
  local selections = fb_utils.get_selected_files(prompt_bufnr, true)
  if vim.tbl_isempty(selections) then
    fb_utils.notify("actions.open", { msg = "No selection to be opened!", level = "INFO", quiet = quiet })
    return
  end

  local cmd = vim.fn.has "win32" == 1 and "start" or vim.fn.has "mac" == 1 and "open" or "xdg-open"
  for _, selection in ipairs(selections) do
    require("plenary.job")
      :new({
        command = cmd,
        args = { selection:absolute() },
      })
      :start()
  end
  actions.close(prompt_bufnr)
end
```

### Neovim version

```markdown
NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.1694082368
```

### Operating system and version

Windows 10

### Steps to reproduce

1. nvim -n
2. e c:\test.lua
3. source %

`test.lua`
```lua
local cmd = 'start'
local selection = [[c:\a.bat]]
require("plenary.job")
  :new({
    command = cmd,
    args = { selection },
  })
  :start()
```

### Expected behavior

execute a.bat

### Actual behavior

cause error.

### Minimal config

```Lua
no config
```

**Comment by jamestrew** [comment]
I believe this is a windows executable `$PATH` issue - not something we can fix with neovim or this plugin.
I'm not a Windows user so I'm not sure how this is done but you need to add `start` into your `$PATH` such that `:echo executable('start')` shows 1.

Otherwise you can used this workaround https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/198#issuecomment-1364608502
