### ISSUE TITLE
Provide an ability to completely disable default mappings

### ISSUE THREAD

**Issue by filakhtov** [nvim-telescope/telescope-file-browser.nvim#322]
I would like to see an ability to completely disable default mappings.

For example, in the telescope itself I can set `default_mappings = {}` and get no default mappings, then add them using `mappings = {}` key, or I can put my preferred mappings into the `default_mappings` right away and then let `mappings` to override things in a more complex scenario.

Either way, I would like to have an ability to not have any defaults and have a complete control over every single possible key bind.

Possible ways to solve this that I've seen in other plugins are:
- override default mappings using `default_mappings = {}`, then extend with `mappings = {}`;
- have a flag that just completely turns off default mappings, something like `disable_default_keybindings` or `custom_only` and then only uses what's defined in the `mappings = {}` option;

Either would work, but the second seems like an easier to understand and is less confusing.

Alternative that exists and is working today is to remove each individual mapping via something like:
```lua
require 'telescope'.setup {
  extensions = {
    file_browser = {
      mappings = {
        i = {
          ['<A-d>'] = false,
        },
      },
    },
  },
}
```
but this is tedious and also not really future-proof - I would have to carefully check every time an update happens.

Does this sound sensible? Are you open to such feature? If so, I would try to implement it and submit a PR. Thanks in advance 🙇🏻‍♂️

**Comment by jamestrew** [comment]
Sorry for the late response

I could add something like `default_mappings` but it ends up being a "for advance users" type option anyways and I'm not sure if there's a ton of demand.
Instead, you should be able to accomplish this by directly accessing the default mappings like so pretty much anywhere in your telescope config.

```lua
require("telescope._extensions.file_browser.config").values.mappings = {}
```
Hope that helps. If not, feel free to re-open.

**Comment by filakhtov** [comment]
> Instead, you should be able to accomplish this by directly accessing the default mappings like so pretty much anywhere in your telescope config.

As an advanced user, that's exactly what I needed. Thanks a lot @jamestrew!
