### ISSUE TITLE
Cursor starts at column 2

### ISSUE THREAD

**Issue by boyo23** [nvim-telescope/telescope-file-browser.nvim#330]
### Description

When opening a file with the telescope-file-browser plugin, whether through a keymap or when opening a directory with Neovim, the cursors start at column 2.

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

### Operating system and version

WSL2 - Debian GNU/Linux 12 (bookworm)

### Steps to reproduce

- `nvim .` 
- `<leader>f` (my keybinding)

### Expected behavior

Cursor starts at column 1.

### Actual behavior

Cursor starts at column 2.

![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/139251819/e96b4119-2625-4d20-8403-748b496a50bf)
![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/139251819/a41ed3ba-0068-44bb-87b8-15e323de5177)

(Sorry I couldn't upload screen record our internet speed is crawling)

### Minimal config

```Lua
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.keymap.set({ "n", "v" }, "<Space>", "<Nop>", { noremap = true, silent = true })

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
  {
    "nvim-telescope/telescope-file-browser.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
    },
    config = function()
      extensions = {
        file_browser = {
          theme = "dropdown",
          grouped = true,
          hidden = true,
          hijack_netrw = true,
          git_status = true,
          prompt_path = true,
          initial_mode = "normal",
          previewer = false,
          mappings = {
            i = { ["<C-o>"] = false },
            n = { ["<o>"] = false },
          },
        },
      },

    pcall(require("telescope").load_extension, "file_browser")

    vim.api.nvim_set_keymap( 'n', '<leader>f', ':Telescope file_browser path=%:p:h select_buffer=true<CR>', { desc = '[F]ile Browser' })

    end
  },
}

require("lazy").setup(plugins, {})
```

**Comment by jamestrew** [comment]
Hey, thanks for the report.
I think this is an issue we're tracking in upstream telescope. The action where using in telescope-file-browser is from upstream so I don't think this is unique to this telescope extension.
https://github.com/nvim-telescope/telescope.nvim/issues/2319

That said, do you experience this every time you open the file?

**Comment by boyo23** [comment]
> That said, do you experience this every time you open the file?

Yes, but I only experience it when using telescope-file-browser.

**Comment by boyo23** [comment]
@jamestrew 

Based on what I observe throughout my day, it appears that this issue only occurs when you are in Telescope's normal mode (i.e., when exiting insert mode within Telescope) and then enter a file. This weird cursor behavior doesn't seem to manifest when entering a file in Telescope without exiting insert mode.

**Comment by jamestrew** [comment]
Ok yeah you're right it's a normal mode issue. It also happens with `:Telescope find_files` for me.
It's definitely an upstream issue that we're tracking so I'll close this one.
