### ISSUE TITLE
New file with ctrl-enter does not fire BufNewFile

### ISSUE THREAD

**Issue by oliverdain** [nvim-telescope/telescope-file-browser.nvim#337]
### Description

I have some `autocmd`s set up on `BufNewFile` to do things like add my company's standard copyright comment. For some reason these don't trigger if the file is created via telescope-file-browser by hitting ctrl-enter.

### Neovim version

```markdown
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az457-787

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
```

### Operating system and version

Linux (Debian Bullseye)

### Steps to reproduce

1. Make sure you have some kind of `autocmd BufNewFile` automation set up.
2. Open telescope-file-browser (e.g. `:Telescope file_browser`) and then type in a filename that does not exist.
3. Create the file by htting ctrl-enter. Note that the `BufNewFile` automation didn't happen.

### Expected behavior

BufNewFile event should be triggered when a new file is created

### Actual behavior

No BufNewFile event triggered

### Minimal config

```Lua
" This is in vimscript - I don't have a Lua config
lua require('telescope').load_extension('file_browser')


" When a new .py file is created enter insert mode and type "I ran!"
autocmd BufNewFile *.py execute "normal iI ran!"
```

**Comment by jamestrew** [comment]
This is because the `BufNewFile` event triggers "when starting to edit a file that doesn't exist" whereas the `create_from_prompt` action bound to `<S-CR>` creates the file, then opens it as a buffer so the file already exists before it is being opened.

If you want to attach some behavior to the `<S-CR>` you can wrap the `create_from_prompt` action in your own function.

```lua
require("telescope").setup({
  extensions = {
    file_browser = {
      mappings = {
        i = {
          ["<S-CR>"] = function(prompt_bufnr)
            fb_actions.create_from_prompt(prompt_bufnr)
            vim.cmd([[normal iIran!]]) -- your custom behavior
          end,
        },
      },
    },
  },
})
```
You can use the `vim.cmd` lua function to execute vimscript if you're not comfortable with lua.

**Comment by jamestrew** [comment]
Thinking more...
I suppose it's possible to manually trigger the `BufNewFile` event but I'm not entirely convinced that this action is in the spirit of this event. When `BufNewFile` trigger, only exists as a buffer until it's explicitly saved.

So yeah, I think the above approach of wrapping `create_from_prompt` is my preferred approach.

**Comment by oliverdain** [comment]
Works for me. Thanks for the quick response and suggested work-around!

**Comment by oliverdain** [comment]
Hi @jamestrew I set up what you suggested and it does trigger. But, when it does I get an error that says, "attempt to index global 'fb_actions' (a nil value)".

Wish I was more familiar with Lua and how this all works. Hoping you maybe have a quick suggestion to fix.

**Comment by jamestrew** [comment]
Ah sorry. I forgot an import.
Here's the same thing with an inline import
```lua
require("telescope").setup({
  extensions = {
    file_browser = {
      mappings = {
        i = {
          ["<A-m>"] = function(prompt_bufnr)
            require("telescope._extensions.file_browser.actions").create_from_prompt(prompt_bufnr)
            vim.cmd([[normal iIran!]])
          end,
        },
      },
    },
  },
})
```

**Comment by oliverdain** [comment]
hmmm... That didn't quite work for me either @jamestrew but now I think it's an issue with UltiSnips. It did enter the text but UltisSnips didn't complete. Oh well, I think I've taken up enough of your time. I might look into how to get it to fire the `BufNewFile` event on trigger as I think that would actually be most useful for my flow; making all my automations work instead of having to duplicate them one by one.

Thanks for your help. If you know how to make the `BufNewFile` thing work a tip would be appreciated. Otherwise, no worries.

**Comment by jamestrew** [comment]
Maybe you can manually trigger BufNewFile in that action? I don't know how in vimscript off the top of my head but I think in lua it's `vim.api.nvim_exec_autocmd('BufNewFile')` or something like that (I'm only on my phone right now). Then you might be able to just use your autocmd normally.

**Comment by oliverdain** [comment]
Hmmm.. Interesting idea. Here's what I did:

```
lua <<LUA
require("telescope").setup({
  extensions = {
    file_browser = {
      mappings = {
        i = {
          ["<S-CR>"] = function(prompt_bufnr)
            require("telescope._extensions.file_browser.actions").create_from_prompt(prompt_bufnr)
            vim.cmd('doautocmd BufNewFile')
          end,
        },
      },
    },
  },
})
LUA
```

But that doesn't work. The file is loaded by my autocmd doesn't run. However, if I then manually do `:doautocmd BufNewFile` in that buffer right after it loads it works as expected. I also tried with `BufNewFile` in double quotes but that didn't work either. There's something about ordering here that I can't work out. Like maybe my `vim.cmd` is firing before the buffer has finished loading or something?

**Comment by jamestrew** [comment]
Using your code does _somewhat_ work for me, not sure why it's not for you but I'm not sure it's good solution either way.
As suspected, it looks like it's a misuse of the `BufNewFile` event since the file actually exists.

I get some edge cases with warning/error message like this
![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/66286082/953bd5ab-59be-41a7-8122-b413df46eb3c)

Here's the config I'm using
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope-file-browser.nvim",
    dependencies = {
      {
        "nvim-telescope/telescope.nvim",
      },
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    config = function()
      require("telescope").setup({
        extensions = {
          file_browser = {
            mappings = {
              i = {
                ["<A-m>"] = function(prompt_bufnr)
                  require("telescope._extensions.file_browser.actions").create_from_prompt(
                    prompt_bufnr
                  )
                  -- vim.api.nvim_exec_autocmds("BufNewFile", {})
                  vim.cmd("doautocmd BufNewFile")
                end,
              },
            },
          },
        },
      })
      require("telescope").load_extension("file_browser")
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("habamax")
vim.opt.hidden = true
vim.opt.showmode = false
vim.cmd([[autocmd BufNewFile *.py execute "normal iI ran!"]])
```

I just put this into a temp file and open neovim with `nvim -u <path/to/config>`

**Comment by oliverdain** [comment]
@jamestrew thanks so much!! I really appreciate you working on this when it's clearly not your bug.

I'm about to head out of town for a week for work but will try to bang on this a bit while I'm gone. Not sure when/if I'll have a chance though. Either way, thanks!
