### ISSUE TITLE
Can't get Telescope File Browser to look like it does in the demo

### ISSUE THREAD

**Issue by nicolasdumitru** [nvim-telescope/telescope-file-browser.nvim#338]
I like the way Telescope File Browser looks in the demo, but I can't find a theme or any other option that gives it that kind of look. I've looked for it both in this repository's README and in Telescope's. How should I get that exact layout for the file browser (and even Telescope in general, if possible)?

**Comment by jamestrew** [comment]
Not my config but I think it's something like
```lua
require('telescope').setup({
  defaults = {
    sorting_strategy = "ascending",
    layout_strategy = "horizontal",
    layout_config = { prompt_position = "top" },
    border = false
  }
})
```
And then applying highlights to these groups (from original config):
https://github.com/fdschmidt93/dotfiles/blob/17fc90360338d34c98287260588048de992d14b8/nvim/.config/nvim/lua/fds/highlights/init.lua#L147-L157

**Comment by nicolasdumitru** [comment]
Thank you for helping me. Telescope now looks exactly the way I wanted and I love it. Not to sound like a smartass, your solution was almost perfect, but for anyone else trying to get that same look, borders have to be set to true (even if false may also work to get the file browser looking right (I'm not sure), setting it to true provides a consistent look with all the Telescope builtins). So the snippet of code that does the trick is:
``` lua
require('telescope').setup({
  defaults = {
    sorting_strategy = "ascending",
    layout_strategy = "horizontal",
    layout_config = { prompt_position = "top" },
    border = true
  }
})
```
This is meant to help anyone else trying to do the same, not take anything away from your input.
