### ISSUE TITLE
Hide Files in git ignore

### ISSUE THREAD

**Issue by SmashMineGame** [nvim-telescope/telescope-file-browser.nvim#34]
How do I hide the files that are ignored by the gitignore? Is this even possible?

**Comment by fdschmidt93** [comment]
`:lua require "telescope".extensions.file_browser.file_browser { respect_gitignore = true }`. This should work analogously when passed via `telescope.setup`.

Please consult the documentation beforehand which is referred to on the README; you'd have found that information via `:h telescope-file-browser.picker`.

**Comment by SmashMineGame** [comment]
it is not working for me, I'm unable to see the hidden files and I'm still able to see the files in my gitignore. Am I passing it incorrectly?

```{lua}
local telescope = require('telescope')

telescope.load_extension('file_browser')

telescope.setup {
  extensions = {
    file_browser = {
      hidden = true,
      respect_gitignore = true
    },
  },
}
```

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope-file-browser.nvim#setup-and-configuration

> -- To get telescope-file-browser loaded and working with telescope,
> -- you need to call load_extension, somewhere after setup function:

**Comment by SmashMineGame** [comment]
Sorry I had noticed this after I made my previous comment, however I had thought it wasn't working because it still shows files and directories that are not tracked by git (like the .git directory). Is there a way to set it to use the `git ls-files` command like Telescope.builtins.git_files uses?

**Comment by fdschmidt93** [comment]
I guess you are looking for `depth = false` applied just like the other comment.

> Please consult the documentation which is referred to on the README in this case :h telescope-file-browser.picker.

I kindly ask you to make an effort to properly read the README and associated documentation before asking questions for which you could have found the answers there. I realize that one not always finds the required info on the first pass, but it provides a lot of context regardless.
