### ISSUE TITLE
Use file-browser as general picker for scripting

### ISSUE THREAD

**Issue by nagy135** [nvim-telescope/telescope-file-browser.nvim#340]
I really like how this picker behaves, jumping around folders etc.

It gave me multiple ideas how to leverage this for my own scripts but what i would like to have is callback function that recieves absolute path with picked file or folder.

Is anything like this currently possible?

**Comment by jamestrew** [comment]
Yeah for sure. You can get the path of the currently selected entry like so
```lua
require("telescope").setup({
  extensions = {
    file_browser = {
      mappings = {
        i = {
          ["<C-m>"] = function(prompt_bufnr)
            local entry = require("telescope.actions.state").get_selected_entry()
            local path = entry.path -- path of the currently selected entry
            -- do whatever you want to do when you hit `<C-m>` (for example)
          end,
        },
      },
    },
  },
})
```

You can look at the source code for "actions" as we call them for more examples and available API usages: https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/actions.lua

**Comment by jamestrew** [comment]
I'll assume this is good to close but feel free to ask questions.

**Comment by nagy135** [comment]
sorry somehow missed this notif, thanks!

**Comment by nagy135** [comment]
This works for me, but i would like to ask if there is a way to not trigger this from within picker itself but "code around it" ...I mean, write a lua function that does stuff, then calls file-browser from some root and on confirmation (<kbd>\<CR\></kbd>) you get a resulting path in a variable.

This would open up so many scripts, because this plugin does the most important part: "travel the filesystem with telescope filtering".

Example (i call this one "thief"):
You set two "roots" ...**from** and **to** ...they are stored in a script variable and then you can call ":ThiefSteal" and it opens basic `find_file` and the file i pick is copied to exactly the same structure of folders on a target (**to**)

Currently I provide those paths manually but this plugin could absolutely make it waaay better :)
