### ISSUE TITLE
Cannot move folder.

### ISSUE THREAD

**Issue by lightseazz** [nvim-telescope/telescope-file-browser.nvim#341]
### Description

I cannot move folder use telescope-file-browser.

I think second commit (f41675f) cause this bug.

I revert to commit da2a20c fix this bug.  

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```

### Operating system and version

OS: Arch Linux x86_64. Kernel: 6.1.63-1-lts

### Steps to reproduce

1. select folder
2. navigation to another folder
3. press keyboard to move

### Expected behavior

Folder is moved flawlessly.

### Actual behavior

I select 2 folders to move to folder "localStorage/"
![c97b6cf707d4ae8af7c5](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/100104776/72dae8f2-f0eb-4168-a050-2c09848757e0)

in this picture, it shows Skipping exsiting with 2 two empty name folders.
![38c1576a33499a17c358](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/100104776/591f461c-8bdb-4757-8523-84eee9a46618)

### Minimal config

```Lua
I have removed all other plugins, except telescope-file-browser and dependacies,clear all custom configs, still not work.
```

**Comment by jamestrew** [comment]
Thanks for reporting, I can reproduce this.
I'll try to get a fix shortly.
