### ISSUE TITLE
Indicator for modified files within git submodule directory? 

### ISSUE THREAD

**Issue by joehdodd** [nvim-telescope/telescope-file-browser.nvim#353]
**Is your feature request related to a problem? Please describe.**

There's a project that I often work in that uses a git submodule to house common code. But I'm noticing that, when I make changes to files within the submodule, telescope-file-browser only shows the directory of the submodule as being modified, not the modified files within it. As this project has hundreds of files, I need a way to quickly visualize files within the submodule that have been modified. Currently, I don't see a way to achieve this with telescope-file-browser.

If this _is_ possible and I've merely glossed over some configuration, then I'll promptly close this. 

Thanks!

**Describe the solution you'd like**

When working in a project using a git submodule, it would be helpful to have an indication of which file in the submodule directory has changed, not just the directory itself.

**Additional context**

Here are some screenshots. The `vim-sub-test` directory shows modification, but the modified `tested.ts` file within the directory does not.
<img width="1381" alt="Screenshot 2024-01-10 at 9 44 46 PM" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/25258729/189974af-76e0-4735-8ecc-0fe739ad1247">
<img width="1377" alt="Screenshot 2024-01-10 at 9 44 55 PM" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/25258729/e896eae1-7222-4214-9b3f-828bde2b421a">

**Comment by jamestrew** [comment]
Thanks, I think this is actually a bug.
If you can try out the PR to fix this that'll be great (#356).

**Comment by joehdodd** [comment]
Yes, that fixed it. Thank you!

<img width="1512" alt="Screenshot 2024-01-13 at 12 39 04 PM" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/25258729/35c290f3-1c5c-4f38-9a5c-6259b68739e4">
<img width="1512" alt="Screenshot 2024-01-13 at 12 39 08 PM" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/25258729/fc9a7e6c-6ac7-4a69-8650-b11bdde23ae7">

**Comment by joehdodd** [comment]
Although, now I'm in my nvim config repo and I'm seeing two "~" next to a file. Is it possible the changes in the submodule branch are causing that, or is it a different issue?
<img width="607" alt="Screenshot 2024-01-13 at 2 59 28 PM" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/25258729/1479c73d-700f-45c3-b89a-c9e6b5946672">

**Comment by jamestrew** [comment]
The `~~` is technically a valid status you could see.
Can you do `git status --porcelain -- .` in that directory? If you see something like `MM lazy-lock.json` (specifically two `M`s), then that's actually expected behavior (`git status --help` has the meaning of it).
If not, it's probably a bug. Although I might need some help with reproducing that on my end so I can see wants happening.
