### ISSUE TITLE
Name Conflict

### ISSUE THREAD

**Issue by mbpowers** [nvim-telescope/telescope-file-browser.nvim#36]
Since this extensions name conflicts with the built in file browser, how do I get telescope to launch this one instead of the built in one? New to lua in nvim so idk if I'm missing something.

There was no question tag so I threw it under feature request, hope that's alright.

**Comment by jamestrew** [comment]
you can open up this file browser with the command `:lua require 'telescope'.extensions.file_browser.file_browser()`

You won't be able to call it with the classic `:Telescope file_browser` command. I think there's some plans to eventually replace the builtin telescope file browser with this one but until then you can use the first command.

create keybinds like
`nnoremap <leader>fb :lua require 'telescope'.extensions.file_browser.file_browser()<CR>`

**Comment by mbpowers** [comment]
Thanks! Looking forward to when this hopefully gets merged into telescope.

Also I just tried remapping some keys as per help docs (very nice btw) and they don't seem to be loading. Also `initial_mode` isn't working either. Any idea as to why? Instead of `n` I also tried `["n"]`.
```
require('telescope').load_extension('file_browser')

local actions = require "telescope.actions"
local fb_actions = require "telescope".extensions.file_browser.actions

require('telescope').setup{
    .
    .
    .
    extensions = {
        file_browser = {
            initial_mode = "normal",
            mappings = {
                n = {
                    ["l"] = fb_actions.open_file,
                    ["h"] = fb_actions.goto_parent_dir,
                    ["n"] = fb_actions.create_file,
                    ["v"] = { "<cmd>echo \"hi\"<cr>", type = "command" },
                }
            }
        }
    }
}
```

**Comment by fdschmidt93** [comment]
@jamestrew many thanks for taking the time to answer questions! Very much appreciated :)

@mbpowers

- `initial_mode = "normal"` doesn't seem to work for me either; I'll look into that.
- I've copied your mappings into my config and they work for me. Is `telescope` updated to the most recent commit? That has only been fixed rather recently.

> You won't be able to call it with the classic :Telescope file_browser command. I think there's some plans to eventually replace the builtin telescope file browser with this one but until then you can use the first command.

This will work again once the `file_browser` has been removed from `telescope`, which also means

> Looking forward to when this hopefully gets merged into telescope.

`telescope-file-browser.nvim` won't get merged into telescope.

**Comment by fdschmidt93** [comment]
`initial_mode` seems to be an upstream issue induced by recent prompt buffer patches. https://github.com/nvim-telescope/telescope.nvim/pull/1600 fixes that.

**Comment by mbpowers** [comment]
@fdschmidt93 Thanks for the help! It's still not working tho :(

I updated with `PlugUpdate` and everything is up to date.

I also tried binding keys in a different extension, with the same results, so at least it is not an issue with file_browser. It is strange because the identical mappings in other sections of my config (in default and pickers) all work as intended.

Just to confirm, are you on the latest version?

I will close this and open a issue over on telescope.
https://github.com/nvim-telescope/telescope.nvim/issues/1638#issue-1090463719

As far as 
> telescope-file-browser.nvim won't get merged into telescope.

Are they just removing the builtin file browser and leaving that functionality to extensions like this, or are they planning on replacing it?

Thanks for your work on this extension!

**Comment by fdschmidt93** [comment]
> Are they just removing the builtin file browser and leaving that functionality to extensions like this, or are they planning on replacing it?

No, the builtin file browser will just be removed from `telescope`. Anyone who wants that functionality should install the extension.

**Comment by mbpowers** [comment]
It seems that `initial_mode` actually is working for me now that the configuration is applying.
