### ISSUE TITLE
Navigate to specified path

### ISSUE THREAD

**Issue by Tai-Mai** [nvim-telescope/telescope-file-browser.nvim#362]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to navigate to a specific directory by passing it to telescope file browser in order to inspect its contents and add a new file. 
My original motivation was that I wanted to be able to navigate to my nvim config folder and add new files. I've since found [telescope project](https://github.com/nvim-telescope/telescope-project.nvim) which does what I want for my nvim config files, however, I'm still missing the option to pass other miscellaneous paths to navigate there.

**Describe the solution you'd like**
A pane in telescope file browser that acts as a "url bar" of sorts where I can see the current path and edit the path to navigate there. Ideally with fuzzy search. 

**Describe alternatives you've considered**
Up until now, I just did it with `:e path/to/file` but I wish there was a way to do it in telescope file browser since I like the UI and file previews.

**Additional context**
I'm using LazyVim.

**Comment by jamestrew** [comment]
You can currently do `:Telescope file_browser path=/path/to/someplace` already.
If you use the option `hijack_netrw=true`, then `:e /path/to/someplace` also opens telescope-file-browser in that path (if given path is a directory).

Does this satisfy your request?

**Comment by Tai-Mai** [comment]
Thanks for the reply!

I've set `hijack_netrw=true` but when I do `:e /path/to/someplace` then [NvimTree](https://github.com/nvim-tree/nvim-tree.lua/) opens the path instead of telescope file browser and I figure out how to prevent it from doing that. Is this an issue with NvimTree then? 

Nice to know that `:Telescope file_browser path=/path/to/someplace` works! I hope you can consider turning that into an address bar like I mentioned above.

**Comment by jamestrew** [comment]
> I've set hijack_netrw=true but when I do :e /path/to/someplace then [NvimTree](https://github.com/nvim-tree/nvim-tree.lua/) opens the path instead of telescope file browser and I figure out how to prevent it from doing that. Is this an issue with NvimTree then?

Oh, there isn't really an issue here. It's just that both nvim-tree and telescope-file-browser is trying to hijack netrw through the same mechanism and there's a conflict. Not much to do other than to only use `hijack_netrw = true` for one of the plugins. The ordering of the plugins being loaded probably plays a role as well.

**Comment by jamestrew** [comment]
For this
> I hope you can consider turning that into an address bar like I mentioned above. 

and
> Ideally with fuzzy search.

I should make sure you know about `:Telescope file_browser files=false` to fuzzy find over directories in your cwd in a folder browser mode. You can also get to this mode with `<C-f>` by default from the usual `:Telescope file_browser`.

I hope that's close enough to what you're looking for.
