### ISSUE TITLE
Searching for a file suddenly works quite different

### ISSUE THREAD

**Issue by svanharmelen** [nvim-telescope/telescope-file-browser.nvim#370]
### Description

When searching for a file in a large folder tree, previously I could type a few chars of a directory to filter on that dir. Then I continued typing a few chars to select the subdir I was looking for. And then I continued with a few chars to select to the file I wanted.

While I was doing this, the (selected) folders would stay visible in the path which made this a very intuitive way to visually search and select the file I needed.

Now after updating this morning this doesn't work anymore. reverting back to this commit fixes the issue: 8839e3f8070dfafa5b0c0e4652700298e7b872c4

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1710088188
```

### Operating system and version

macOS 14.3.1

### Steps to reproduce

Use the minimal config and type a few chars...

### Expected behavior

I typed `nv` to select the `nvim` dir, followed by `lu` to select the `lua` dir and then `se` to select the settings file:

<img width="521" alt="image" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/4171547/6c31e0b1-474c-43b0-bd2d-9c61245c2ff3">

### Actual behavior

I types the same chars in the same project, but now I get nothing:

<img width="665" alt="image" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/4171547/51dfcaf3-925b-454c-b1e7-1bc664cf21fe">

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope-file-browser.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("telescope").setup({
        extensions = {
          file_browser = {
            auto_depth = true,
            display_stat = false,
            grouped = true,
            hide_parent_dir = true,
            select_buffer = true,
          },
      })
      require("telescope").load_extension("file_browser")
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
Thanks, I think I've fixed. Let me know if that's not the case.

**Comment by svanharmelen** [comment]
Thanks @jamestrew, works as expected again 👍🏻
