### ISSUE TITLE
(question): how to disable search bar

### ISSUE THREAD

**Issue by PowerzinBR** [nvim-telescope/telescope-file-browser.nvim#377]
Hello everyone, i'm kinda new exploring plugins, and i didn't find any thing related to that in the documentation (please warn me if it does exist), so. **How to disable the search bar (if it's possible) in the file browser?**

![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/140966320/8bdfb878-69df-456d-8a79-0dce8ed13fdc)

Thanks for answering me, i guess :D

**Comment by jamestrew** [comment]
Telescope (and by extension, this plugin) is a fuzzy finder over lists - so searching is kind of the whole point.
If you're not interested in searching, then this plugin might not be for you.

**Comment by PowerzinBR** [comment]
I understand, thanks for the answer jamestrew.
