### ISSUE TITLE
Do not create files on empty result

### ISSUE THREAD

**Issue by AndreasNasman** [nvim-telescope/telescope-file-browser.nvim#381]
Hi! 👋

Is it possible to suppress the behavior of creating files when pressing Enter if no results are found? I sometimes mistype a filename, which results in no matches, and if I press Enter without noticing, a file is created that I don't want. Can I disable this behavior and only create files using explicit `create` actions?

Example: I want to open the `temp.lua` file but accidentally type `temm` and press Enter, creating a `temm` file I don't want.
<img width="1552" alt="image" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/17124245/028a92f9-b584-4d60-987f-8581593684ae">
![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/17124245/f54f20b7-45e7-4238-b946-00271d5f4ccf)
![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/17124245/8f95cb08-89ab-4f32-a02c-95a47293deba)
<img width="1552" alt="image" src="https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/17124245/c098e2a0-6ebf-4c68-b556-563483c57488">

**Comment by jamestrew** [comment]
Yeah I can see this as being annoying.
I'll add an option to disable this feature. I'll try to do this in the over the next couple of days.

**Comment by jamestrew** [comment]
Added the option `create_from_prompt`. It defaults to true to preserve existing behavior but you can set it to `false` in your config to disable creating files/folders from the prompt when there are no results.
