### ISSUE TITLE
The date of file preview is displayed incorrectly in Windows

### ISSUE THREAD

**Issue by IC0hO** [nvim-telescope/telescope-file-browser.nvim#392]
### Description

![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/43652659/401446db-6a42-4346-9ef4-e4077f22fbcf)
Dates are displayed starting with 5<d4><c2>

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

### Operating system and version

Windows 11 22631.3593

### Steps to reproduce

1. Open Neovim in the `$HOME` directory.
2. Open the file manager using the `:Telescope file_browser` command Close the file browser.
3. When displaying any file information, the date is wrong.

### Actual behavior

![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/43652659/e6161ee5-c79b-4459-8cd4-b9c85c6a621e)

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope-file-browser.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("telescope").setup({})
      require("telescope").load_extension("file_browser")
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
I believe this is caused by system locale rather than it being Windows related. It's trying to render the abbreviated month name using the system locale but your terminal or font or something isn't handling the encoding well.

I'm not too confident this is something I can fix on our end.

**Comment by jamestrew** [comment]
That is an option but I'm not sure about forcing English month names on everyone. And the idea of the `display_stat` is to mirror `ls -la` so I'd prefer to not change the format to something more universal either.

> If the display is abnormal, it is better to give the user the option to close it.

You can disable the previewer entirely using the `previewer = false` option to the `file_browser` config or just `:Telescope file_browser previewer=false`.

You can also use `preview = { ls_short = true }` option to make the previewer not show stats.

I hope that's a good enough compromise.

**Comment by jamestrew** [comment]
No worries!
