### ISSUE TITLE
feat: Add the create, rename, move, delete event convenient LSP docking.

### ISSUE THREAD

**Issue by chaozwn** [nvim-telescope/telescope-file-browser.nvim#396]
**Is your feature request related to a problem? Please describe.**
When we use LSPS, we often hope that the lsp can modify other files synchronously when we rename them. Therefore, we need such an event.

**Describe the solution you'd like**
There are better access plug-ins here, as long as we give the corresponding entry.
issue link: https://github.com/antosha417/nvim-lsp-file-operations/issues/33
Refer to the pr link：https://github.com/antosha417/nvim-lsp-file-operations/pull/29/files

If we can throw an event hook, I can help with the development of another plug-in.

**Comment by jamestrew** [comment]
Thanks for the suggestion! I think this is probably something we should (should've) have natively.
I'll try to work on this.

**Comment by jamestrew** [comment]
If you can give https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/400 a try that'll be helpful.
