### ISSUE TITLE
Error Date encoded

### ISSUE THREAD

**Issue by Barmaley0** [nvim-telescope/telescope-file-browser.nvim#398]
### Description

When opening

### Neovim version

```markdown
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```

### Operating system and version

Windows 10

### Steps to reproduce

Some problems with date display
![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/133758633/c9c5e255-0a65-4f85-b7c7-6f16784d69fd)

### Expected behavior

![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/133758633/86032e25-d09d-4cfa-b5ed-d828517db89a)

### Actual behavior

When opening. Please tell me, has anyone encountered this problem and how did you solve it?

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope-file-browser.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("telescope").setup({})
      require("telescope").load_extension("file_browser")
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by Barmaley0** [comment]
my config
![image](https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/133758633/4801ca0b-fe0c-4d0e-808f-f40c36f3a194)

**Comment by jamestrew** [comment]
See this issue https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/392
