### ISSUE TITLE
Media Issue: showcase GIFs of telescope-file-browser.nvim

### ISSUE THREAD

**Issue by fdschmidt93** [nvim-telescope/telescope-file-browser.nvim#53]
This issue showcases several file system operations ("`actions`") of `telescope-file-browser.nvim` and hosts the GIFs referred to throughout the repository.

**Comment by fdschmidt93** [comment]
**File Creation**

https://user-images.githubusercontent.com/39233597/148996650-10efe060-e856-4922-850c-41af4e100d68.mp4

**Comment by fdschmidt93** [comment]
### Copying Files

#### Single File

Copying the currently selected file

https://user-images.githubusercontent.com/39233597/149009373-a5e6e89b-637e-4645-bb66-7bc9e78d01a7.mp4

#### Multi-Selected Files/Folders

1. Multi-select some files
2. Switch to folder browser 
3. Select a folder
4. Go to another folder
5. Copy to current `path` in file browser mode

https://user-images.githubusercontent.com/39233597/149009545-c7839658-69fa-48d0-abef-7402bd8cd546.mp4

**Comment by fdschmidt93** [comment]
### File/Folder Moving

1. Multi-select files
2. Toggle `folder_browser`
3. Select a folder
4. Go to another (target) folder
5. `fb_actions.move` multi-select to `path`

https://user-images.githubusercontent.com/39233597/149010291-41bbb12e-cb97-41a8-8eab-c7a63094b6c3.mp4



https://user-images.githubusercontent.com/39233597/149010279-a622a3a3-3b20-47ec-a439-d7db22aa0637.mp4

**Comment by fdschmidt93** [comment]
### Remove Files

### Single File

https://user-images.githubusercontent.com/39233597/149012737-e6638a3b-0d26-4a1d-8686-4d0e1e09f97f.mp4

### Multi-Selection

Nuke it ;)

https://user-images.githubusercontent.com/39233597/149012845-7a40eba8-a2e4-46ad-bfeb-e85bd09820c9.mp4

**Comment by fdschmidt93** [comment]
### Rename

#### Single File

Uploading fb_action_rename.mp4…

#### Multi-Selection

https://user-images.githubusercontent.com/39233597/149014240-adfb45d6-9fb8-4b51-b9ea-4cbf2354b31e.mp4

**Comment by fdschmidt93** [comment]
### Demo of Webpage as proper GIF

(currently multi copying, may change)

![fb_action_copy_multi](https://user-images.githubusercontent.com/39233597/149016073-6fcc9383-a761-422b-be40-17d4b854cd3c.gif)

**Comment by ikerurda** [comment]
The video in
> ### Remove Files
> ### Single File
>  fb_bulk_rename.mp4 

is wrong.

Thanks for everything, good job! :)

**Comment by fdschmidt93** [comment]
Dragged the wrong file into the issue :laughing: 

I'll delete our comments some time tomorrow for cleanliness, thanks for pointing this out :)

**Comment by fdschmidt93** [comment]
No need to thank me, I'm just glad if people raise issues in civilized fashsions and with repros. Otherwise just trying to do my best with my "vision" in mind :laughing:
