### ISSUE TITLE
path/cwd options produce absolute paths on initial load

### ISSUE THREAD

**Issue by gegoune** [nvim-telescope/telescope-file-browser.nvim#54]
### Description

On initial load of file browser files are incorrectly prefixed with absolute path while no paths should be visible at all (just filenames).

### Neovim version

```markdown
NVIM v0.7.0-dev+870-g43b95b543
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.1

### Steps to reproduce

1. nvim --clean -u minimal.lua
2. Hit `-` to open file browser
3. Observe "Actual behaviour"
4. Go one level up by hitting `../`
5. Return to previous directory (optional)
6. Observe "Expected behaviour"

### Expected behavior

See files without paths as it should be displaying relatively to current buffer's directory.

### Actual behavior

Files displayed with absolute paths, for example:

`/Users/gegoune/dotfiles/nvim/after/plugin`

(after changing directory from initial one files are not prefixed with absolute path any more)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')

  vim.keymap.set('n', '-', function()
    require('telescope').extensions.file_browser.file_browser {
      path = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ':.:h'),
      cwd = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(0), ':.:h'),
    }
  end)
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Thanks for reporting!

I'll try to look into this next week, I guess it's related to many issues around `path_display` in the entry maker

See also https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/47

with maybe a band aid fix here: https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/47#pullrequestreview-845419286

**Comment by gegoune** [comment]
Seems to be fixed by https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/47.

Thanks!
