### ISSUE TITLE
Incompatible with dressing.nvim

### ISSUE THREAD

**Issue by AckslD** [nvim-telescope/telescope-file-browser.nvim#66]
### Description

Not sure if this issue should be raised here or at https://github.com/stevearc/dressing.nvim but these plugins don't work well together when for example creating new files. See below.

### Neovim version

```markdown
NVIM v0.7.0-dev+890-g574a582202
Build type: RelWithDebInfo
LuaJIT 2.0.5
```

### Operating system and version

arch linux 5.15.12-arch1-1

### Steps to reproduce

1. have `telescope-file-browser.nvim` and `dressing.nvim` installed.
2. create a new file using the browser
3. enter the file name and click enter

### Expected behavior

The telescope prompt to stay open and no error being raised.

### Actual behavior

You get the error:
```
Error executing vim.schedule lua callback: ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:851: Invalid buffer id: 7
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:851: in function 'reset_prompt'
        ...pack/packer/opt/telescope.nvim/lua/telescope/pickers.lua:874: in function 'refresh'
        ....nvim/lua/telescope/_extensions/file_browser/actions.lua:82: in function 'on_confirm'
        ...e/pack/packer/start/dressing.nvim/lua/dressing/input.lua:72: in function ''
        vim.lua: in function ''
        vim.lua: in function <vim.lua:0>
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      'stevearc/dressing.nvim',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
I guess the problem here is that `vim.ui.input` with `dressing.nvim` triggers an autocmd which closes the picker.

While `telescope-file-browser` _could_ wrap `vim.ui.input` into `noautocmd` or `eventignore = "all"`, I think `vim.ui` overrides should take care of that, assuming of course there's no need for autocmd during `vim.ui.input` (not sure what the use case would be). I guess you could also make the case that `telescope` should maybe try to avoid using autocommands for closing the picker to begin with.

As a band aid fix, manually mapping the below should circumvent the issue for you for the time being.
```lua
["<A-c>"] = function(prompt_bufnr)
  vim.cmd(string.format([[noautocmd require "telescope".extensions.file_browser.actions.create(%)]], prompt_bufnr)
end
```
(haven't tried it, if no syntax error I think it should work)

**Comment by AckslD** [comment]
Thanks @fdschmidt93, so would you say that this is something that should be handled better in `dressing.nvim`?

I tried the temporary solution (added a missing `)`) but seems to still give the same behaviour unfortunately.

**Comment by AckslD** [comment]
Thanks @fdschmidt93, so would you say that this is something that should be fixed in `dressing.nvim`?

Fixing some small typos the above fix works:
```lua
["<A-c>"] = function(prompt_bufnr)
  vim.cmd(string.format([[noautocmd lua require("telescope").extensions.file_browser.actions.create(%d)]], prompt_bufnr))
end
```
however there are other things such as confirming deleting files etc which doesn't work so well. I think the best for now would be to have an ability to disable dressing for certain buffers. I'll check if this is possible or add this as a feature request.

Anyway closing this since it's not really a `telescope-file-browser` issue.

Thanks for the help! :)

**Comment by fdschmidt93** [comment]
Confirmation of deletion of files also now uses `vim.ui.input`, so the same fix should also work just as well.

Maybe with lua autocmds there will also be api for noautocmd, then we could factor that in from within telescope file browser more smoothly I suppose.

**Comment by AckslD** [comment]
Thanks @fdschmidt93 that seems to also work, in then end I did:
```lua
local actions = {
    ["i"] = {
        ["<A-c>"] = 'create',
        ["<A-r>"] = 'rename',
        ["<A-m>"] = 'move',
        ["<A-y>"] = 'copy',
        ["<A-d>"] = 'remove',
        ["<C-o>"] = 'open',
        ["<C-g>"] = 'goto_parent_dir',
        ["<C-e>"] = 'goto_home_dir',
        ["<C-w>"] = 'goto_cwd',
        ["<C-t>"] = 'change_cwd',
        ["<C-f>"] = 'toggle_browser',
        ["<C-h>"] = 'toggle_hidden',
        ["<C-s>"] = 'toggle_all',
    },
    ["n"] = {
        ["c"] = 'create',
        ["r"] = 'rename',
        ["m"] = 'move',
        ["y"] = 'copy',
        ["d"] = 'remove',
        ["o"] = 'open',
        ["g"] = 'goto_parent_dir',
        ["e"] = 'goto_home_dir',
        ["w"] = 'goto_cwd',
        ["t"] = 'change_cwd',
        ["f"] = 'toggle_browser',
        ["h"] = 'toggle_hidden',
        ["s"] = 'toggle_all',
    },
}

local function get_action(action)
    return function(prompt_bufnr)
        vim.cmd(string.format([[noautocmd lua require("telescope").extensions.file_browser.actions.%s(%d)]], action, prompt_bufnr))
    end
end

local mappings = {}
for _, mode in ipairs({'i', 'n'}) do
    local keys = {}
    for key, action in pairs(actions[mode]) do
        keys[key] = get_action(action)
    end
    mappings[mode] = keys
end

require("telescope").setup({
    extensions = {
        file_browser = {
            mappings = mappings,
        },
    },
})
```
