### ISSUE TITLE
Fuzzy search for a file, or a folder in the project directory, then open its parent directory in the telescope-file-browser

### ISSUE THREAD

**Issue by quantum-booty** [nvim-telescope/telescope-file-browser.nvim#69]
Tree like browsers like LuaTree frustrates me a bit when I know exactly the name of the folder or a file, but I still have to traverse down the tree to find it.
It would be nice if I could fuzzy search for the file or folder, then open the telescope-file-browser in the directory which the file or folder resides in.

**Comment by fdschmidt93** [comment]
Does the `folder_browser` not work for you? See [workflow](https://github.com/nvim-telescope/telescope-file-browser.nvim#workflow) of README and GIF.

Toggling between file and folder browser is currently mapped by default to `<C-f>` in insert and `f` in normal mode, respectively. (Mappings are being revisited, possibly subject to change).

Closing this because I believe it's just an oversight of the README. Let me know in case there's more to do here.

**Comment by quantum-booty** [comment]
@fdschmidt93 thanks I see! Can I make folder_browser the default finder?

**Comment by ikerurda** [comment]
```lua
require"telescope".setup {
  ...
  extensions = {
    file_browser = {
      ...
      files = false,
    }
  }
}
```

**Comment by quantum-booty** [comment]
Also can I select a result from for example require('telescope.builtin').git_files() and open the folder in the file_browser? I guess this is what I had in mind originally.

**Comment by ikerurda** [comment]
```lua
local open_in_fb = function(prompt_bufnr)
  local action_state = require "telescope.actions.state"
  local Path = require "plenary.Path"
  local actions = require "telescope.actions"
  local fb = require("telescope").extensions.file_browser.file_browser

  local entry_path = Path:new(action_state.get_selected_entry()[1])
  local path = entry_path:is_dir() and entry_path:absolute() or entry_path:parent():absolute()
  actions._close(prompt_bufnr, true)
  fb { path = path }
end

...
require"telescope".setup {
  ...
  extensions = {
    file_browser = {
      mappings = {
        i = { ["<a-e>"] = open_in_fb },
        n = { ["<a-e>"] = open_in_fb },
      }
    }
  }
}
...
```
This should work, don't know if there's a better way of doing it tho

**Comment by quantum-booty** [comment]
Thanks I think it should be ```plenary.path``` instead of ```plenary.Path```, and it only works if the ```file=true```.
But it works!

**Comment by quantum-booty** [comment]
@ikerurda Is it possible to move the cursor on to the file as well?

e.g. I search for telescope in git-files, then open the file_browser.
![image](https://user-images.githubusercontent.com/28958399/149658152-2c9ea59c-d511-4457-ae25-6ea7bdbb7193.png)
The cursor is on the first line.
![image](https://user-images.githubusercontent.com/28958399/149658209-5c1d97af-4815-4b43-b9a7-3c72ea6ebd68.png)
However it would be nice if it can be placed onto the telescope file directly, like this:
![image](https://user-images.githubusercontent.com/28958399/149658223-21217931-ba38-477f-adec-c5b717d59c00.png)

**Comment by quantum-booty** [comment]
I think this would be a very nice workflow, worth adding it into the readme.

**Comment by ikerurda** [comment]
I've been trying, but haven't found a way of doing it...
Hope somebody can help you :)

**Comment by fdschmidt93** [comment]
I could what we could add is opting-in that the `folder_browser` shows one of (i) files (ii) folders or (iii) files and folders and then, whenever one of the three is selected you go to the corresponding folder.

For files, I suppose it makes sense to place the cursor on the selected file.

Once this is natively supported from within the folder browser, I'm happy to add this to the readme.

**Comment by quantum-booty** [comment]
I think it makes more sense to support it as a function rather than another file browser mode, because having it as a functions allows me to open file_browser with various pickers like grep_string and lsp reference.

**Comment by fdschmidt93** [comment]
> I think it makes more sense to support it as a function rather than another file browser mode, because having it as a functions allows me to open file_browser with various pickers like grep_string and lsp reference.

Any user is free to customize the extension as they like; that is, such a function is something for the [wiki](https://github.com/nvim-telescope/telescope-file-browser.nvim/wiki) and then every one can tailor the function to their use case rather than having another action natively. `telescope-file-browser` should ship with primarily "native" features.

For what I elaborated above, having something like this built-in, see #73
