### ISSUE TITLE
file_browser not opening the current buffer path

### ISSUE THREAD

**Issue by aniketgm** [nvim-telescope/telescope-file-browser.nvim#75]
### Description

When I do a `:Telescope file_browser path='%:p:h'`, it does not open path/directory structure of the current open buffer.
I also tried with double quotes, meaning, path="%:p:h", still same issue.

See below GIF for more info.
![Peek 2022-01-18 23-45](https://user-images.githubusercontent.com/14215698/149996075-6cb54991-97ee-469a-9101-43e122c4605a.gif)

Issue described by GIF shall be sufficient. Let me know if more info is required.

### Neovim version

```markdown
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.11.0-46-generic 20.04.1-Ubuntu

### Steps to reproduce

1. Open a file
2. Run the command `:Telescope file_browser path='%:p:h'`

### Actual behavior

The current buffer path should be opened, which is not happening.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          'nvim-telescope/telescope-file-browser.nvim',
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('file_browser')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Apologies, I've realized that the `'` must go. It should be `:Telescope file_browser path=%:p:h` which works for me.

Many thanks for reporting! :) I've already corrected it on the README. Closing since I'm 99.9% sure that solves the issue. Please let me know in case that's not the case.

Once again, thanks!

**Comment by aniketgm** [comment]
Well, make it 100% sure. That did it thanks.
