### ISSUE TITLE
How do I get the theme from the showcase issue?

### ISSUE THREAD

**Issue by brandoncc** [nvim-telescope/telescope-file-browser.nvim#76]
The theme from the showcase issue is really nice, how do I get that theme? Is it just totally a custom theme and not available in sample code?

Thanks!

**Comment by fdschmidt93** [comment]
> Is it just totally a custom theme and not available in sample code?

Yes, it's a bit of a custom theme.

See my [reply](https://www.reddit.com/r/neovim/comments/s1qzkq/comment/hsc00tp/?utm_source=share&utm_medium=web2x&context=3) to the same question on reddit. With the right telescope highlighting groups it should be straightforward to fit something like this to your theme.

**Comment by fdschmidt93** [comment]
Closing as I'm optimistic the referral is sufficient; another user successfully managed to tie the look to his theme. Happy to help on specific aspects.

**Comment by brandoncc** [comment]
Okay, I'm not much of a designer so I was hoping there would be some pluggable code.

Thanks for your response.
