### ISSUE TITLE
Error when running `:Telescope file_browser path='%:p:h'`

### ISSUE THREAD

**Issue by knpwrs** [nvim-telescope/telescope-file-browser.nvim#77]
### Description

I have `telescope-file-browser.nvim` set up, and calling `:Telescope file_browser` works, but calling `:Telescope file_browser path='%:p:h'` (as designated in the README).

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 12.1

### Steps to reproduce

1. Run `:Telescope file_browser path='%:p:h'`

### Expected behavior

I should get a file browser window starting in the directory of the current file.

### Actual behavior

An error is printed and I am presented with an empty file browser window:

```
[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:468: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:416>
```
![image](https://user-images.githubusercontent.com/174864/150002946-ead9a48d-9913-4adc-9085-77a298e5fbd7.png)

**Comment by fdschmidt93** [comment]
Thanks for reporting! Apologies for the slight error in the vim cmd, it should be `:Telescope file_browser path=%:p:h`

I've only ~20mins ago fixed this issue as someone else was slightly faster in noticing the problem.

https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/75

**Comment by knpwrs** [comment]
Excellent, thank you!
