### ISSUE TITLE
Close keymap window if escape is pressed

### ISSUE THREAD

**Issue by LamprosPitsillos** [nvim-telescope/telescope-file-browser.nvim#80]
I would love it if the help box (keymap window) would go away if i press `esc`. I always look for help and then want it to go but pressing escape just closes Telescope.
I don't see a reason why it would stay even after I type something since its even hiding most of the screen.  
Thanks for an amazing plugin!

**Comment by fdschmidt93** [comment]
What help box? You mean the one that shows the keymaps?

**Comment by LamprosPitsillos** [comment]
Yes yes , the key map window

**Comment by fdschmidt93** [comment]
Ok, either close it by pressing the keys you've pressed to show it or scroll with the results with `<C-n>` or `<C-p>`.

Any `telescope` action would also close it via an autocmd. Just not `ESC` here though you could map it yourself to toggle the keymap float.

In any case, closing. Question answered and I guess it's also more of a `telescope.nvim` issue.
