### ISSUE TITLE
Expose default action

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope-file-browser.nvim#85]
Hey @fdschmidt93, awesome work I really like how this turned out, unfortunately just now I've begun actually integrating it in my workflow. Should have done that long time ago. 

**Is your feature request related to a problem? Please describe.**

I'm trying to remap "<c-l>" and "l" to run the default action.

**Describe the solution you'd like**

expose the default action through fb_actions.default

**Describe alternatives you've considered**

pretty much copy the replace_if

**Comment by tami5** [comment]
Maybe actions.select_default is what I'm looking for

**Comment by fdschmidt93** [comment]
What do you mean by the default action here? Following if it's a directory or opening if it's a file? If so, what's the use case?

> I'm trying to remap "" and "l" to run the default action.

Remappings can be done as with any other picker and are described on the README [here](https://github.com/nvim-telescope/telescope-file-browser.nvim#remappings)?

Sorry, I don't follow.

**Comment by tami5** [comment]
> Following if it's a directory or opening if it's a file

Exactly, it turns out that actions.select_default is what I needed and there is no need to reexpose the default action. Maybe hint it ? but I believe after #65 there will be no need for it because the new default would be sufficient.

Thanks @fdschmidt93
