### ISSUE TITLE
Sorting option that separates directories and files

### ISSUE THREAD

**Issue by brotherkaif** [nvim-telescope/telescope-file-browser.nvim#90]
**Is your feature request related to a problem? Please describe.**
The sorting method of the file browser currently sorts directories and files in a combined manner. It also displays the listing in descending order. This is different to the general conventions adopted by other code editors and file browsing tools.

Currently, files and directories are all sorted as follows:
```
C-file.md     
› C-directory/
B-file.md     
› B-directory/
A-file.md     
› A-directory/
› ../         
```

However, In vim/neovim's built-in `netrw` plugin, the same listing is sorted as follows:
```
A-directory/
B-directory/
C-directory/
A-file.md
B-file.md
C-file.md
```

In VS Code's explorer, it is listed as:
```
> A-directory
> B-directory
> C-directory
A-file.md
B-file.md
C-file.md
```

In GitHub's repo view:
```
A-directory
B-directory
C-directory
A-file.md
B-file.md
C-file.md
```

The same is true with many other file browsers out there. Whilst I appreciate that the Telescope file browser is intended to be navigated using fuzzy searches, it can be difficult to _visually_ get your bearings whilst browsing a project. Especially if you have been browsing the same directory using a different tool.

**Describe the solution you'd like**
The option to sort directories and files separately and in ascending order (so that it matches the conventions of other file browsers).

So that the listing is as follows:
```
› A-directory/
› B-directory/
› C-directory/
A-file.md
B-file.md
C-file.md
› ../
```

**Describe alternatives you've considered**
Not sure if there are any alternative approaches I could try.

**Additional context**
n/a

Thanks!

**Comment by fdschmidt93** [comment]
As per `:h fb_picker.file_browser`

To have initial sorting as desired, `:Telescope file_browser grouped=true` or `grouped = true` to the lua function calling the picker or extension setup.

Closing as I'm pretty sure that's it. Let me know in case it's not.

**Comment by brotherkaif** [comment]
Doh! You're correct, this can already be controlled via the options. To get the behaviour described above:
```
require('telescope').setup({
    extensions = {
      file_browser = {
	grouped = true,
	sorting_strategy = 'ascending',
      },
    },
})
```

Thanks for your help!
