### ISSUE TITLE
Add "quiet" config option to suppress action confirmation print statements

### ISSUE THREAD

**Issue by steve-lorimer** [nvim-telescope/telescope-file-browser.nvim#91]
**Is your feature request related to a problem? Please describe.**

Whenever I execute a file action (eg: delete a file), I find the additional confirmation at the end of the action, which then requires an additional enter to dismiss, breaks my workflow

eg:
```
These files are going to be deleted:
/tmp/foo
Remove selected files [y/N]: y
/tmp/foo has been removed!                             \ these 2 lines
Press ENTER or type command to continue                / 
```

ie: the following print statements in `actions.lua`

```
print(string.format("%s has been moved!", filename))
print(string.format("\n%s has been removed!", p:absolute()))
```

**Describe the solution you'd like**

I would like a "quiet" config option which prevents the action confirmation print statement being output

**Comment by fdschmidt93** [comment]
Yeah, we should probably do this as part of #72

**Comment by fdschmidt93** [comment]
Ok, I've looked a bit more into this and it's surprisingly tricky; it's essentially a mechanism such that `(n)vim` can be redrawn after confirmation.

> To reduce the number of hit-enter prompts:
> - Set 'cmdheight' to 2 or higher.
> - Add flags to 'shortmess'.
> - Reset 'showcmd' and/or 'ruler'.
> - Make sure `:echo` text is within |v:echospace| screen cells.

See `:h hit-enter prompts`.

So as an intermediate solution, one thing to do would be something akin to

```lua
local silent_action = function(action)
  return function(prompt_bufnr)
    local cmd = string.format([[lua require "telescope".extensions.file_browser.%s(%d)]], action, prompt_bufnr)
    vim.cmd(cmd)
  end
end

require("telescope").setup {
  extensions = {
    file_browser = {
      mappings = {
        ["i"] = {
          ["<A-y>"] = silent_action "copy",
        },
      },
    },
  },
}
```

I'll try to see how `hit-enter` can be cleanly avoided, though a super clean solution is not immediately apparent (cf. suggestions to reduce no. of prompts..).

**Comment by jamestrew** [comment]
Yeah I was struggling with this very thing in the i/o refactoring in #72 trying to deal with this issue and #87.

**Comment by fdschmidt93** [comment]
As an update: see https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/87#issuecomment-1077431257

**Comment by steve-lorimer** [comment]
Thank you!

**Comment by fdschmidt93** [comment]
You're welcome :)

I know a `quiet` option may still be desirable, but just to note any notifications now should be much less intrusive as `hit-enter` should now be properly avoided everywhere it could pop up (in at the very least any practical situation).
