### ISSUE TITLE
why do we need to and move files to the current path 

### ISSUE THREAD

**Issue by vbaswin** [nvim-telescope/telescope-file-browser.nvim#92]
Newbie, so if this is already resolved please help. I am unable to copy files to buffer and paste it in another location.
It is only showing option to copy or move to the current directory.
We can specify the directories only in the folder mode but it is not wise to just copy the entire folder. Please help

**Comment by fdschmidt93** [comment]
You multi-select files you want to move or copy, then in

* `file_browser`: move/copy to the currently opened folder
* `folder_browser`: move/copy to the currently selected folder

Otherwise, I don't understand your question. Please phrase more clearly.

**Comment by vbaswin** [comment]
first thanks for replying.
if we use y key  in normal mode it will copy the selected file to the current directory in which it is placed ie: replacing it.
instead i want to copy it to buffer and paste it else where which is not possible.
This is possible only in the case of folders but that too would copy the entire files which I don't need. 
If you are able to implement this it would really be a life saver.
Thank you

**Comment by fdschmidt93** [comment]
Can you please say more clearly what you functionality you are trying to achieve?

> instead i want to copy it to buffer and paste it else where which is not possible.

I can only guess what you mean here.

**Comment by vbaswin** [comment]
I just want to copy file or folder then paste to another location after searching  n the browser rather than specifying the destination at the copy time itself.
That ie want to save to buffer and after fuzzy finding the folder i need i can paste it like vifm.

**Comment by fdschmidt93** [comment]
Have you closely watched the gifs of usage and read the README? Multi-selections persist throughout a session across directories and file or folder browser.

In other words, a typical workflow looks like this: you multi-select files to move or copy, then you go to or select the folder via the folder browser.

Sorry, closing, please carefully read documentation of `telescope.nvim` and `telescope-file-browser.nvim`. If I understand correctly, what you are trying to achieve is one of the core features of this extension.

After that, in case what you require is still a valid feature request, please ping me here and clearly lay out what functionality we should provide.

**Comment by vbaswin** [comment]
Yeah you are right.The thing is we need to select the files and we have to move to the folder we want to paste ok. This is my mistake thankyou for being helpful.

**Comment by fdschmidt93** [comment]
You can also multi-select files/folders and then move/paste to the selected folder in folder browser mode. Not strictly required to actually go to the folder.

**Comment by vbaswin** [comment]
Thankyou. Saved my day!

**Comment by vbaswin** [comment]
Hi sorry to bother again but how do I select files. I used s key to select ig then when i press m for move it is saying nothing currently selected to be moved.

Used s key to select  and as you said turned folder browser mode and when I pressed y for copying the selected files to currently opened folder nvim got stuck. and had to close it and reopen again this happens whenever I am trying to copy. 
I watched your gifs many times but couldn't figure out what keys your are pressing to select, copy and paste. Please do help again.

**Comment by vbaswin** [comment]
Ok so tab selects files and folders.

The extension is so slow. There is huge lag when copying and moving files even if they are small. 
Is it due to low processing power.
Cause it is taking a hell of time to manage files.

Thank you

**Comment by fdschmidt93** [comment]
> Ok so tab selects files and folders. It took me a long time to figure this out. It would be really helpful to list this in readme.

As mentioned above, please familiarize yourself with documentation of not only `telescope-file-browser.nvim` but also `telescope.nvim`.

> The extension is so slow. There is huge lag when copying and moving files even if they are small.
Is it due to low processing power.

It maybe slow if you copy/move a **lot** of files. I've moved/copied gigabytes in a heartbeat, though not as many files as such. `telescope-file-browser.nvim` is not necessarily meant to replace all of your file management needs, as there is only so much you can do from within neovim without jumping through large hoops. It's more thought of supporting quick actions from within your programming workflow.

That said, I'd kindly ask you not to spam and check docs carefully yourself.

**Comment by vbaswin** [comment]
ok
