### ISSUE TITLE
add option to auto focus on the entry of current buffer when the displayed directory is the directory of current file

### ISSUE THREAD

**Issue by ZhiyuanLck** [nvim-telescope/telescope-file-browser.nvim#95]
## Reasons

A **new operation mode** is entered when fb is started with its own key mappings, it is glad for me to map '-' to open fb **in the  current directory** and use the buffer key mappings. For example, I set the initial mode to `normal` and map `L` to open on the right, and it will **not occupy** the mapping of `<m-l>` or `<c-l>` . It is more convenient than run commands in the command line! But I think there can be a little improvement, it will be better if it can try to focus on the current buffer when someone prefers to **operate on the file of current buffer**.

Since fb can make use of the **fuzzy search** of upstream, the initial selection of entry may be not so important.

## Some details

The possible way is to provide an option such as `auto_focus`, so that users can set it to true in the `setup` function or **pass it to the startup function**.

Note that hidden files need to be toggled if the file of current buffer is a hidden file.

Well, it is better to also control `auto_focus` by adding a new action `auto_focus_toggle` :)

**Comment by fdschmidt93** [comment]
> Well, it is better to also control auto_focus by adding a new action auto_focus_toggle :)

Why would that need a toggle?

I guess it can be more or less straightforwardly added to the `plenary` `file_browser` here

https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/master/lua/telescope/_extensions/file_browser/finders.lua

You'd iterate the results to try to find the entry of the current buffer and then set `default_selection_index` of the picker. The handover to the picker here would also have to be managed.

PR welcome :)

**Comment by ZhiyuanLck** [comment]
@fdschmidt93 I managed to it, but stucked at how to pass the value of `default_selection_index` to  the picker, cauze I don't know how to get the current picker in a finder and it seems that `opts` are passed to the picker by `Picker:new` which is before the finder is specified.

Another problem is that calling `Picker:set_selection` has no effect after the call of `Picker:find()`.
```lua
  local picker = pickers.new(opts, {
    prompt_title = opts.files and "File Browser" or "Folder Browser",
    results_title = opts.files and Path:new(opts.path):make_relative(cwd) .. os_sep or "Results",
    finder = fb_finder.finder(opts),
    previewer = conf.file_previewer(opts),
    sorter = conf.file_sorter(opts),
  })
  picker:find()
  picker:set_selection(picker:get_row(3))
```
Maybe it is wrong to manually update the selection index. I'm quite new to the code of telescope and wish to get more help.

**Comment by fdschmidt93** [comment]
It's a bit more easily inspected in a PR :) but great to hear you've already progressed so far.

Another way would be just to instantiate the finder and then extract the `default_selection_index` before `pickers.new` to add it to `opts` that are passed to the picker. Probably easiest.

Does that make sense? Happy to comment on a PR.

That way, I guess you'd only have to make sure that if `auto_focus` (maybe `select_buffer` is more adequately verbose? not sure) set, the `plenary` `file_browser` is launched.

> Maybe it is wrong to manually update the selection index. I'm quite new to the code of telescope and wish to get more help.

No, here it is the correct way of progressing. That's why we'd have to use plenary to have a synchronized finder. For `file_browser`, it should be always fast enough with modern machines (except for `depth=false` or `depth>1`).

**Comment by ZhiyuanLck** [comment]
I wonder where the `opts` is passed to `browser_files`. The following code in `pickers.lua` give me the error that `attempt to call field `entry_maker` (a nil value) 
```lua
  local finder = fb_finder.finder(opts)
  if opts.files then
    print(finder._browse_files())
  end
```

The `entry_maker` option is set in `fb_finders.finder`, while inside `__call` metamethod, I find no opts passed to corresponding functions.
```lua
        if self.files then
          self._finder = self:_browse_files()
        else
          self._finder = self:_browse_folders()
        end
```
And I find no where the options are passed. So how do these options flow through?

Follow your instruction, my idea is to instantiate a finder and get its `results` (does the order of results is the order of display?), then I can test if the inital path is the directory of current buffer by `opts.path` and extract correct index by itering over `results`.

**Comment by fdschmidt93** [comment]
`fb_finder` is `opts`, if you will. In lua, `self:_browse_files()` `:` signifies that `self` is the first `arg` to `_browse_files`, analogously to class methods.

> Follow your instruction, my idea is to instantiate a finder and get its results (does the order of results is the order of display?), then I can test if the initial path is the directory of current buffer by opts.path and extract correct index by itering over results.

The initial order of results is respected at initial drawing, yes (assuming I understand your question correctly).

Yes, something along these lines should work.
